// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"
)

// SetFake set fake values.
func (s *CommonServiceItem) SetFake() {
	{
		{
			s.Index.SetFake()
		}
	}
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.ModifiedAt = time.Now()
		}
	}
	{
		{
			s.Provider.SetFake()
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemDestinationSettings) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.Value = "string"
		}
	}
	{
		{
			s.Disabled.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemDestinationSettingsType) SetFake() {
	*s = CommonServiceItemDestinationSettingsTypeEmail
}

// SetFake set fake values.
func (s *CommonServiceItemGroupSettings) SetFake() {
	{
		{
			s.Destinations = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Destinations = append(s.Destinations, elem)
			}
		}
	}
	{
		{
			s.Disabled.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemProvider) SetFake() {
	{
		{
			s.Class.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemProviderClass) SetFake() {
	*s = CommonServiceItemProviderClassSaknoticedestination
}

// SetFake set fake values.
func (s *CommonServiceItemRoutingSettings) SetFake() {
	{
		{
			s.MatchLabels = nil
			for i := 0; i < 0; i++ {
				var elem CommonServiceItemRoutingSettingsMatchLabelsItem
				{
					elem.SetFake()
				}
				s.MatchLabels = append(s.MatchLabels, elem)
			}
		}
	}
	{
		{
			s.SourceID = "string"
		}
	}
	{
		{
			s.TargetGroupID = "string"
		}
	}
	{
		{
			s.PriorityRank = int(0)
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemSettings) SetFake() {
	var variant CommonServiceItemDestinationSettings

	{
		variant.SetFake()
	}
	s.SetCommonServiceItemDestinationSettings(variant)
}

// SetFake set fake values.
func (s *CreateCommonServiceItemCreated) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DeleteCommonServiceItemOK) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetCommonServiceItemOK) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetCommonServiceItemStatusResponse) SetFake() {
	{
		{
			s.NotificationStatus.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetCommonServiceItemStatusResponseNotificationStatus) SetFake() {
	{
		{
			s.IsValid = true
		}
	}
	{
		{
			s.ModifiedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *GetSimpleNotificationHistoryResponse) SetFake() {
	{
		{
			s.NotificationHistory.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Icon) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.URL.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Scope.SetFake()
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListCommonServiceItemsResponse) SetFake() {
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.Count.SetFake()
		}
	}
	{
		{
			s.Total.SetFake()
		}
	}
	{
		{
			s.CommonServiceItems = nil
			for i := 0; i < 0; i++ {
				var elem CommonServiceItem
				{
					elem.SetFake()
				}
				s.CommonServiceItems = append(s.CommonServiceItems, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListSimpleNotificationHistoriesResponse) SetFake() {
	{
		{
			s.NotificationHistories = nil
			for i := 0; i < 0; i++ {
				var elem NotificationHistory
				{
					elem.SetFake()
				}
				s.NotificationHistories = append(s.NotificationHistories, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListSourcesResponse) SetFake() {
	{
		{
			s.Sources = nil
			for i := 0; i < 0; i++ {
				var elem ListSourcesResponseSourcesItem
				{
					elem.SetFake()
				}
				s.Sources = append(s.Sources, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *ListSourcesResponseSourcesItem) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
}

// SetFake set fake values.
func (s *NilIcon) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *NotificationHistory) SetFake() {
	{
		{
			s.RequestID = "string"
		}
	}
	{
		{
			s.SourceID = "string"
		}
	}
	{
		{
			s.Statuses = nil
			for i := 0; i < 0; i++ {
				var elem NotificationStatus
				{
					elem.SetFake()
				}
				s.Statuses = append(s.Statuses, elem)
			}
		}
	}
	{
		{
			s.ReceivedAt = time.Now()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NotificationMessage) SetFake() {
	{
		{
			s.Body = "string"
		}
	}
	{
		{
			s.Color = "string"
		}
	}
	{
		{
			s.ColorCode = "string"
		}
	}
	{
		{
			s.IconURL = "string"
		}
	}
	{
		{
			s.ImageURL = "string"
		}
	}
	{
		{
			s.Title = "string"
		}
	}
}

// SetFake set fake values.
func (s *NotificationStatus) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorInfo = "string"
		}
	}
	{
		{
			s.NotificationRequestID = "string"
		}
	}
	{
		{
			s.GroupID = "string"
		}
	}
	{
		{
			s.DestinationID = "string"
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
	{
		{
			s.UpdatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *NotificationStatusStatus) SetFake() {
	*s = NotificationStatusStatus0
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPostCommonServiceItemRequest) SetFake() {
	var elem PostCommonServiceItemRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPutCommonServiceItemRequest) SetFake() {
	var elem PutCommonServiceItemRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPutCommonServiceItemRequestCommonServiceItemSettings) SetFake() {
	var elem PutCommonServiceItemRequestCommonServiceItemSettings
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPutCommonServiceItemRoutingReorderRequest) SetFake() {
	var elem PutCommonServiceItemRoutingReorderRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptSendNotificationMessageRequest) SetFake() {
	var elem SendNotificationMessageRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *PostCommonServiceItemRequest) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Provider.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PostCommonServiceItemRequestCommonServiceItemProvider) SetFake() {
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PostCommonServiceItemRequestCommonServiceItemProviderClass) SetFake() {
	*s = PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticedestination
}

// SetFake set fake values.
func (s *PostCommonServiceItemRequestCommonServiceItemSettings) SetFake() {
	var variant CommonServiceItemDestinationSettings

	{
		variant.SetFake()
	}
	s.SetCommonServiceItemDestinationSettings(variant)
}

// SetFake set fake values.
func (s *PutCommonServiceItemRequest) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRequestCommonServiceItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description = "string"
		}
	}
	{
		{
			s.Tags = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.Tags = append(s.Tags, elem)
			}
		}
	}
	{
		{
			s.Icon.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRequestCommonServiceItemSettings) SetFake() {
	var variant CommonServiceItemDestinationSettings

	{
		variant.SetFake()
	}
	s.SetCommonServiceItemDestinationSettings(variant)
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingReorderRequest) SetFake() {
	{
		{
			s.Orders = nil
			for i := 0; i < 0; i++ {
				var elem PutCommonServiceItemRoutingReorderRequestOrdersItem
				{
					elem.SetFake()
				}
				s.Orders = append(s.Orders, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) SetFake() {
	{
		{
			s.PriorityRank = int(0)
		}
	}
	{
		{
			s.RoutingID = "string"
		}
	}
}

// SetFake set fake values.
func (s *ReorderRoutingAccepted) SetFake() {
	{
		{
			s.IsOk.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SendNotificationMessageRequest) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *SendNotificationMessageResponse) SetFake() {
	{
		{
			s.IsOk = true
		}
	}
}

// SetFake set fake values.
func (s *UpdateCommonServiceItemOK) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}
