// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/CommonServiceItem
type CommonServiceItem struct {
	Index       OptInt                    `json:"Index"`
	ID          string                    `json:"ID"`
	Name        string                    `json:"Name"`
	Description string                    `json:"Description"`
	Settings    CommonServiceItemSettings `json:"Settings"`
	CreatedAt   time.Time                 `json:"CreatedAt"`
	ModifiedAt  time.Time                 `json:"ModifiedAt"`
	Provider    CommonServiceItemProvider `json:"Provider"`
	Icon        *CommonServiceItemIcon    `json:"Icon"`
	Tags        []string                  `json:"Tags"`
}

// GetIndex returns the value of Index.
func (s *CommonServiceItem) GetIndex() OptInt {
	return s.Index
}

// GetID returns the value of ID.
func (s *CommonServiceItem) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *CommonServiceItem) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CommonServiceItem) GetDescription() string {
	return s.Description
}

// GetSettings returns the value of Settings.
func (s *CommonServiceItem) GetSettings() CommonServiceItemSettings {
	return s.Settings
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CommonServiceItem) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *CommonServiceItem) GetModifiedAt() time.Time {
	return s.ModifiedAt
}

// GetProvider returns the value of Provider.
func (s *CommonServiceItem) GetProvider() CommonServiceItemProvider {
	return s.Provider
}

// GetIcon returns the value of Icon.
func (s *CommonServiceItem) GetIcon() *CommonServiceItemIcon {
	return s.Icon
}

// GetTags returns the value of Tags.
func (s *CommonServiceItem) GetTags() []string {
	return s.Tags
}

// SetIndex sets the value of Index.
func (s *CommonServiceItem) SetIndex(val OptInt) {
	s.Index = val
}

// SetID sets the value of ID.
func (s *CommonServiceItem) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *CommonServiceItem) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CommonServiceItem) SetDescription(val string) {
	s.Description = val
}

// SetSettings sets the value of Settings.
func (s *CommonServiceItem) SetSettings(val CommonServiceItemSettings) {
	s.Settings = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CommonServiceItem) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *CommonServiceItem) SetModifiedAt(val time.Time) {
	s.ModifiedAt = val
}

// SetProvider sets the value of Provider.
func (s *CommonServiceItem) SetProvider(val CommonServiceItemProvider) {
	s.Provider = val
}

// SetIcon sets the value of Icon.
func (s *CommonServiceItem) SetIcon(val *CommonServiceItemIcon) {
	s.Icon = val
}

// SetTags sets the value of Tags.
func (s *CommonServiceItem) SetTags(val []string) {
	s.Tags = val
}

// Ref: #/components/schemas/CommonServiceItemDestinationSettings
type CommonServiceItemDestinationSettings struct {
	Type     CommonServiceItemDestinationSettingsType `json:"Type"`
	Value    string                                   `json:"Value"`
	Disabled OptBool                                  `json:"Disabled"`
}

// GetType returns the value of Type.
func (s *CommonServiceItemDestinationSettings) GetType() CommonServiceItemDestinationSettingsType {
	return s.Type
}

// GetValue returns the value of Value.
func (s *CommonServiceItemDestinationSettings) GetValue() string {
	return s.Value
}

// GetDisabled returns the value of Disabled.
func (s *CommonServiceItemDestinationSettings) GetDisabled() OptBool {
	return s.Disabled
}

// SetType sets the value of Type.
func (s *CommonServiceItemDestinationSettings) SetType(val CommonServiceItemDestinationSettingsType) {
	s.Type = val
}

// SetValue sets the value of Value.
func (s *CommonServiceItemDestinationSettings) SetValue(val string) {
	s.Value = val
}

// SetDisabled sets the value of Disabled.
func (s *CommonServiceItemDestinationSettings) SetDisabled(val OptBool) {
	s.Disabled = val
}

type CommonServiceItemDestinationSettingsType string

const (
	CommonServiceItemDestinationSettingsTypeEmail   CommonServiceItemDestinationSettingsType = "email"
	CommonServiceItemDestinationSettingsTypeWebhook CommonServiceItemDestinationSettingsType = "webhook"
)

// AllValues returns all CommonServiceItemDestinationSettingsType values.
func (CommonServiceItemDestinationSettingsType) AllValues() []CommonServiceItemDestinationSettingsType {
	return []CommonServiceItemDestinationSettingsType{
		CommonServiceItemDestinationSettingsTypeEmail,
		CommonServiceItemDestinationSettingsTypeWebhook,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CommonServiceItemDestinationSettingsType) MarshalText() ([]byte, error) {
	switch s {
	case CommonServiceItemDestinationSettingsTypeEmail:
		return []byte(s), nil
	case CommonServiceItemDestinationSettingsTypeWebhook:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CommonServiceItemDestinationSettingsType) UnmarshalText(data []byte) error {
	switch CommonServiceItemDestinationSettingsType(data) {
	case CommonServiceItemDestinationSettingsTypeEmail:
		*s = CommonServiceItemDestinationSettingsTypeEmail
		return nil
	case CommonServiceItemDestinationSettingsTypeWebhook:
		*s = CommonServiceItemDestinationSettingsTypeWebhook
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CommonServiceItemGroupSettings
type CommonServiceItemGroupSettings struct {
	Destinations []string `json:"Destinations"`
	Disabled     OptBool  `json:"Disabled"`
}

// GetDestinations returns the value of Destinations.
func (s *CommonServiceItemGroupSettings) GetDestinations() []string {
	return s.Destinations
}

// GetDisabled returns the value of Disabled.
func (s *CommonServiceItemGroupSettings) GetDisabled() OptBool {
	return s.Disabled
}

// SetDestinations sets the value of Destinations.
func (s *CommonServiceItemGroupSettings) SetDestinations(val []string) {
	s.Destinations = val
}

// SetDisabled sets the value of Disabled.
func (s *CommonServiceItemGroupSettings) SetDisabled(val OptBool) {
	s.Disabled = val
}

type CommonServiceItemIcon struct{}

type CommonServiceItemProvider struct {
	Class CommonServiceItemProviderClass `json:"Class"`
}

// GetClass returns the value of Class.
func (s *CommonServiceItemProvider) GetClass() CommonServiceItemProviderClass {
	return s.Class
}

// SetClass sets the value of Class.
func (s *CommonServiceItemProvider) SetClass(val CommonServiceItemProviderClass) {
	s.Class = val
}

type CommonServiceItemProviderClass string

const (
	CommonServiceItemProviderClassSaknoticedestination CommonServiceItemProviderClass = "saknoticedestination"
	CommonServiceItemProviderClassSaknoticegroup       CommonServiceItemProviderClass = "saknoticegroup"
	CommonServiceItemProviderClassSaknoticerouting     CommonServiceItemProviderClass = "saknoticerouting"
)

// AllValues returns all CommonServiceItemProviderClass values.
func (CommonServiceItemProviderClass) AllValues() []CommonServiceItemProviderClass {
	return []CommonServiceItemProviderClass{
		CommonServiceItemProviderClassSaknoticedestination,
		CommonServiceItemProviderClassSaknoticegroup,
		CommonServiceItemProviderClassSaknoticerouting,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CommonServiceItemProviderClass) MarshalText() ([]byte, error) {
	switch s {
	case CommonServiceItemProviderClassSaknoticedestination:
		return []byte(s), nil
	case CommonServiceItemProviderClassSaknoticegroup:
		return []byte(s), nil
	case CommonServiceItemProviderClassSaknoticerouting:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CommonServiceItemProviderClass) UnmarshalText(data []byte) error {
	switch CommonServiceItemProviderClass(data) {
	case CommonServiceItemProviderClassSaknoticedestination:
		*s = CommonServiceItemProviderClassSaknoticedestination
		return nil
	case CommonServiceItemProviderClassSaknoticegroup:
		*s = CommonServiceItemProviderClassSaknoticegroup
		return nil
	case CommonServiceItemProviderClassSaknoticerouting:
		*s = CommonServiceItemProviderClassSaknoticerouting
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CommonServiceItemRoutingSettings
type CommonServiceItemRoutingSettings struct {
	MatchLabels   []CommonServiceItemRoutingSettingsMatchLabelsItem `json:"MatchLabels"`
	SourceID      string                                            `json:"SourceID"`
	TargetGroupID string                                            `json:"TargetGroupID"`
	PriorityRank  int                                               `json:"PriorityRank"`
}

// GetMatchLabels returns the value of MatchLabels.
func (s *CommonServiceItemRoutingSettings) GetMatchLabels() []CommonServiceItemRoutingSettingsMatchLabelsItem {
	return s.MatchLabels
}

// GetSourceID returns the value of SourceID.
func (s *CommonServiceItemRoutingSettings) GetSourceID() string {
	return s.SourceID
}

// GetTargetGroupID returns the value of TargetGroupID.
func (s *CommonServiceItemRoutingSettings) GetTargetGroupID() string {
	return s.TargetGroupID
}

// GetPriorityRank returns the value of PriorityRank.
func (s *CommonServiceItemRoutingSettings) GetPriorityRank() int {
	return s.PriorityRank
}

// SetMatchLabels sets the value of MatchLabels.
func (s *CommonServiceItemRoutingSettings) SetMatchLabels(val []CommonServiceItemRoutingSettingsMatchLabelsItem) {
	s.MatchLabels = val
}

// SetSourceID sets the value of SourceID.
func (s *CommonServiceItemRoutingSettings) SetSourceID(val string) {
	s.SourceID = val
}

// SetTargetGroupID sets the value of TargetGroupID.
func (s *CommonServiceItemRoutingSettings) SetTargetGroupID(val string) {
	s.TargetGroupID = val
}

// SetPriorityRank sets the value of PriorityRank.
func (s *CommonServiceItemRoutingSettings) SetPriorityRank(val int) {
	s.PriorityRank = val
}

type CommonServiceItemRoutingSettingsMatchLabelsItem struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
}

// GetName returns the value of Name.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) SetValue(val string) {
	s.Value = val
}

// CommonServiceItemSettings represents sum type.
type CommonServiceItemSettings struct {
	Type                                 CommonServiceItemSettingsType // switch on this field
	CommonServiceItemDestinationSettings CommonServiceItemDestinationSettings
	CommonServiceItemGroupSettings       CommonServiceItemGroupSettings
	CommonServiceItemRoutingSettings     CommonServiceItemRoutingSettings
}

// CommonServiceItemSettingsType is oneOf type of CommonServiceItemSettings.
type CommonServiceItemSettingsType string

// Possible values for CommonServiceItemSettingsType.
const (
	CommonServiceItemDestinationSettingsCommonServiceItemSettings CommonServiceItemSettingsType = "CommonServiceItemDestinationSettings"
	CommonServiceItemGroupSettingsCommonServiceItemSettings       CommonServiceItemSettingsType = "CommonServiceItemGroupSettings"
	CommonServiceItemRoutingSettingsCommonServiceItemSettings     CommonServiceItemSettingsType = "CommonServiceItemRoutingSettings"
)

// IsCommonServiceItemDestinationSettings reports whether CommonServiceItemSettings is CommonServiceItemDestinationSettings.
func (s CommonServiceItemSettings) IsCommonServiceItemDestinationSettings() bool {
	return s.Type == CommonServiceItemDestinationSettingsCommonServiceItemSettings
}

// IsCommonServiceItemGroupSettings reports whether CommonServiceItemSettings is CommonServiceItemGroupSettings.
func (s CommonServiceItemSettings) IsCommonServiceItemGroupSettings() bool {
	return s.Type == CommonServiceItemGroupSettingsCommonServiceItemSettings
}

// IsCommonServiceItemRoutingSettings reports whether CommonServiceItemSettings is CommonServiceItemRoutingSettings.
func (s CommonServiceItemSettings) IsCommonServiceItemRoutingSettings() bool {
	return s.Type == CommonServiceItemRoutingSettingsCommonServiceItemSettings
}

// SetCommonServiceItemDestinationSettings sets CommonServiceItemSettings to CommonServiceItemDestinationSettings.
func (s *CommonServiceItemSettings) SetCommonServiceItemDestinationSettings(v CommonServiceItemDestinationSettings) {
	s.Type = CommonServiceItemDestinationSettingsCommonServiceItemSettings
	s.CommonServiceItemDestinationSettings = v
}

// GetCommonServiceItemDestinationSettings returns CommonServiceItemDestinationSettings and true boolean if CommonServiceItemSettings is CommonServiceItemDestinationSettings.
func (s CommonServiceItemSettings) GetCommonServiceItemDestinationSettings() (v CommonServiceItemDestinationSettings, ok bool) {
	if !s.IsCommonServiceItemDestinationSettings() {
		return v, false
	}
	return s.CommonServiceItemDestinationSettings, true
}

// NewCommonServiceItemDestinationSettingsCommonServiceItemSettings returns new CommonServiceItemSettings from CommonServiceItemDestinationSettings.
func NewCommonServiceItemDestinationSettingsCommonServiceItemSettings(v CommonServiceItemDestinationSettings) CommonServiceItemSettings {
	var s CommonServiceItemSettings
	s.SetCommonServiceItemDestinationSettings(v)
	return s
}

// SetCommonServiceItemGroupSettings sets CommonServiceItemSettings to CommonServiceItemGroupSettings.
func (s *CommonServiceItemSettings) SetCommonServiceItemGroupSettings(v CommonServiceItemGroupSettings) {
	s.Type = CommonServiceItemGroupSettingsCommonServiceItemSettings
	s.CommonServiceItemGroupSettings = v
}

// GetCommonServiceItemGroupSettings returns CommonServiceItemGroupSettings and true boolean if CommonServiceItemSettings is CommonServiceItemGroupSettings.
func (s CommonServiceItemSettings) GetCommonServiceItemGroupSettings() (v CommonServiceItemGroupSettings, ok bool) {
	if !s.IsCommonServiceItemGroupSettings() {
		return v, false
	}
	return s.CommonServiceItemGroupSettings, true
}

// NewCommonServiceItemGroupSettingsCommonServiceItemSettings returns new CommonServiceItemSettings from CommonServiceItemGroupSettings.
func NewCommonServiceItemGroupSettingsCommonServiceItemSettings(v CommonServiceItemGroupSettings) CommonServiceItemSettings {
	var s CommonServiceItemSettings
	s.SetCommonServiceItemGroupSettings(v)
	return s
}

// SetCommonServiceItemRoutingSettings sets CommonServiceItemSettings to CommonServiceItemRoutingSettings.
func (s *CommonServiceItemSettings) SetCommonServiceItemRoutingSettings(v CommonServiceItemRoutingSettings) {
	s.Type = CommonServiceItemRoutingSettingsCommonServiceItemSettings
	s.CommonServiceItemRoutingSettings = v
}

// GetCommonServiceItemRoutingSettings returns CommonServiceItemRoutingSettings and true boolean if CommonServiceItemSettings is CommonServiceItemRoutingSettings.
func (s CommonServiceItemSettings) GetCommonServiceItemRoutingSettings() (v CommonServiceItemRoutingSettings, ok bool) {
	if !s.IsCommonServiceItemRoutingSettings() {
		return v, false
	}
	return s.CommonServiceItemRoutingSettings, true
}

// NewCommonServiceItemRoutingSettingsCommonServiceItemSettings returns new CommonServiceItemSettings from CommonServiceItemRoutingSettings.
func NewCommonServiceItemRoutingSettingsCommonServiceItemSettings(v CommonServiceItemRoutingSettings) CommonServiceItemSettings {
	var s CommonServiceItemSettings
	s.SetCommonServiceItemRoutingSettings(v)
	return s
}

type CreateCommonServiceItemCreated struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
	Success           OptBool           `json:"Success"`
	IsOk              OptBool           `json:"is_ok"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *CreateCommonServiceItemCreated) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// GetSuccess returns the value of Success.
func (s *CreateCommonServiceItemCreated) GetSuccess() OptBool {
	return s.Success
}

// GetIsOk returns the value of IsOk.
func (s *CreateCommonServiceItemCreated) GetIsOk() OptBool {
	return s.IsOk
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *CreateCommonServiceItemCreated) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}

// SetSuccess sets the value of Success.
func (s *CreateCommonServiceItemCreated) SetSuccess(val OptBool) {
	s.Success = val
}

// SetIsOk sets the value of IsOk.
func (s *CreateCommonServiceItemCreated) SetIsOk(val OptBool) {
	s.IsOk = val
}

type DeleteCommonServiceItemOK struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *DeleteCommonServiceItemOK) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *DeleteCommonServiceItemOK) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}

// Ref: #/components/schemas/Error
type Error struct {
	IsFatal   OptBool   `json:"is_fatal"`
	Serial    OptString `json:"serial"`
	Status    OptString `json:"status"`
	ErrorCode OptString `json:"error_code"`
	ErrorMsg  OptString `json:"error_msg"`
}

// GetIsFatal returns the value of IsFatal.
func (s *Error) GetIsFatal() OptBool {
	return s.IsFatal
}

// GetSerial returns the value of Serial.
func (s *Error) GetSerial() OptString {
	return s.Serial
}

// GetStatus returns the value of Status.
func (s *Error) GetStatus() OptString {
	return s.Status
}

// GetErrorCode returns the value of ErrorCode.
func (s *Error) GetErrorCode() OptString {
	return s.ErrorCode
}

// GetErrorMsg returns the value of ErrorMsg.
func (s *Error) GetErrorMsg() OptString {
	return s.ErrorMsg
}

// SetIsFatal sets the value of IsFatal.
func (s *Error) SetIsFatal(val OptBool) {
	s.IsFatal = val
}

// SetSerial sets the value of Serial.
func (s *Error) SetSerial(val OptString) {
	s.Serial = val
}

// SetStatus sets the value of Status.
func (s *Error) SetStatus(val OptString) {
	s.Status = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *Error) SetErrorCode(val OptString) {
	s.ErrorCode = val
}

// SetErrorMsg sets the value of ErrorMsg.
func (s *Error) SetErrorMsg(val OptString) {
	s.ErrorMsg = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

type GetCommonServiceItemOK struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *GetCommonServiceItemOK) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *GetCommonServiceItemOK) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}

// Ref: #/components/schemas/GetCommonServiceItemStatusResponse
type GetCommonServiceItemStatusResponse struct {
	NotificationStatus GetCommonServiceItemStatusResponseNotificationStatus `json:"NotificationStatus"`
}

// GetNotificationStatus returns the value of NotificationStatus.
func (s *GetCommonServiceItemStatusResponse) GetNotificationStatus() GetCommonServiceItemStatusResponseNotificationStatus {
	return s.NotificationStatus
}

// SetNotificationStatus sets the value of NotificationStatus.
func (s *GetCommonServiceItemStatusResponse) SetNotificationStatus(val GetCommonServiceItemStatusResponseNotificationStatus) {
	s.NotificationStatus = val
}

type GetCommonServiceItemStatusResponseNotificationStatus struct {
	IsValid    bool      `json:"IsValid"`
	ModifiedAt time.Time `json:"ModifiedAt"`
}

// GetIsValid returns the value of IsValid.
func (s *GetCommonServiceItemStatusResponseNotificationStatus) GetIsValid() bool {
	return s.IsValid
}

// GetModifiedAt returns the value of ModifiedAt.
func (s *GetCommonServiceItemStatusResponseNotificationStatus) GetModifiedAt() time.Time {
	return s.ModifiedAt
}

// SetIsValid sets the value of IsValid.
func (s *GetCommonServiceItemStatusResponseNotificationStatus) SetIsValid(val bool) {
	s.IsValid = val
}

// SetModifiedAt sets the value of ModifiedAt.
func (s *GetCommonServiceItemStatusResponseNotificationStatus) SetModifiedAt(val time.Time) {
	s.ModifiedAt = val
}

// Ref: #/components/schemas/GetSimpleNotificationHistoryResponse
type GetSimpleNotificationHistoryResponse struct {
	NotificationHistory NotificationHistory `json:"NotificationHistory"`
}

// GetNotificationHistory returns the value of NotificationHistory.
func (s *GetSimpleNotificationHistoryResponse) GetNotificationHistory() NotificationHistory {
	return s.NotificationHistory
}

// SetNotificationHistory sets the value of NotificationHistory.
func (s *GetSimpleNotificationHistoryResponse) SetNotificationHistory(val NotificationHistory) {
	s.NotificationHistory = val
}

// Ref: #/components/schemas/ListCommonServiceItemsResponse
type ListCommonServiceItemsResponse struct {
	From               OptInt              `json:"From"`
	Count              OptInt              `json:"Count"`
	Total              OptInt              `json:"Total"`
	CommonServiceItems []CommonServiceItem `json:"CommonServiceItems"`
}

// GetFrom returns the value of From.
func (s *ListCommonServiceItemsResponse) GetFrom() OptInt {
	return s.From
}

// GetCount returns the value of Count.
func (s *ListCommonServiceItemsResponse) GetCount() OptInt {
	return s.Count
}

// GetTotal returns the value of Total.
func (s *ListCommonServiceItemsResponse) GetTotal() OptInt {
	return s.Total
}

// GetCommonServiceItems returns the value of CommonServiceItems.
func (s *ListCommonServiceItemsResponse) GetCommonServiceItems() []CommonServiceItem {
	return s.CommonServiceItems
}

// SetFrom sets the value of From.
func (s *ListCommonServiceItemsResponse) SetFrom(val OptInt) {
	s.From = val
}

// SetCount sets the value of Count.
func (s *ListCommonServiceItemsResponse) SetCount(val OptInt) {
	s.Count = val
}

// SetTotal sets the value of Total.
func (s *ListCommonServiceItemsResponse) SetTotal(val OptInt) {
	s.Total = val
}

// SetCommonServiceItems sets the value of CommonServiceItems.
func (s *ListCommonServiceItemsResponse) SetCommonServiceItems(val []CommonServiceItem) {
	s.CommonServiceItems = val
}

// Ref: #/components/schemas/ListSimpleNotificationHistoriesResponse
type ListSimpleNotificationHistoriesResponse struct {
	NotificationHistories []NotificationHistory `json:"NotificationHistories"`
}

// GetNotificationHistories returns the value of NotificationHistories.
func (s *ListSimpleNotificationHistoriesResponse) GetNotificationHistories() []NotificationHistory {
	return s.NotificationHistories
}

// SetNotificationHistories sets the value of NotificationHistories.
func (s *ListSimpleNotificationHistoriesResponse) SetNotificationHistories(val []NotificationHistory) {
	s.NotificationHistories = val
}

// Ref: #/components/schemas/ListSourcesResponse
type ListSourcesResponse struct {
	Sources []ListSourcesResponseSourcesItem `json:"Sources"`
}

// GetSources returns the value of Sources.
func (s *ListSourcesResponse) GetSources() []ListSourcesResponseSourcesItem {
	return s.Sources
}

// SetSources sets the value of Sources.
func (s *ListSourcesResponse) SetSources(val []ListSourcesResponseSourcesItem) {
	s.Sources = val
}

type ListSourcesResponseSourcesItem struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *ListSourcesResponseSourcesItem) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *ListSourcesResponseSourcesItem) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *ListSourcesResponseSourcesItem) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ListSourcesResponseSourcesItem) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/NotificationHistory
type NotificationHistory struct {
	RequestID  string               `json:"request_id"`
	SourceID   string               `json:"source_id"`
	Statuses   []NotificationStatus `json:"statuses"`
	ReceivedAt time.Time            `json:"received_at"`
	Message    NotificationMessage  `json:"message"`
}

// GetRequestID returns the value of RequestID.
func (s *NotificationHistory) GetRequestID() string {
	return s.RequestID
}

// GetSourceID returns the value of SourceID.
func (s *NotificationHistory) GetSourceID() string {
	return s.SourceID
}

// GetStatuses returns the value of Statuses.
func (s *NotificationHistory) GetStatuses() []NotificationStatus {
	return s.Statuses
}

// GetReceivedAt returns the value of ReceivedAt.
func (s *NotificationHistory) GetReceivedAt() time.Time {
	return s.ReceivedAt
}

// GetMessage returns the value of Message.
func (s *NotificationHistory) GetMessage() NotificationMessage {
	return s.Message
}

// SetRequestID sets the value of RequestID.
func (s *NotificationHistory) SetRequestID(val string) {
	s.RequestID = val
}

// SetSourceID sets the value of SourceID.
func (s *NotificationHistory) SetSourceID(val string) {
	s.SourceID = val
}

// SetStatuses sets the value of Statuses.
func (s *NotificationHistory) SetStatuses(val []NotificationStatus) {
	s.Statuses = val
}

// SetReceivedAt sets the value of ReceivedAt.
func (s *NotificationHistory) SetReceivedAt(val time.Time) {
	s.ReceivedAt = val
}

// SetMessage sets the value of Message.
func (s *NotificationHistory) SetMessage(val NotificationMessage) {
	s.Message = val
}

// Ref: #/components/schemas/NotificationMessage
type NotificationMessage struct {
	Body      string `json:"body"`
	Color     string `json:"color"`
	ColorCode string `json:"color_code"`
	IconURL   string `json:"icon_url"`
	ImageURL  string `json:"image_url"`
	Title     string `json:"title"`
}

// GetBody returns the value of Body.
func (s *NotificationMessage) GetBody() string {
	return s.Body
}

// GetColor returns the value of Color.
func (s *NotificationMessage) GetColor() string {
	return s.Color
}

// GetColorCode returns the value of ColorCode.
func (s *NotificationMessage) GetColorCode() string {
	return s.ColorCode
}

// GetIconURL returns the value of IconURL.
func (s *NotificationMessage) GetIconURL() string {
	return s.IconURL
}

// GetImageURL returns the value of ImageURL.
func (s *NotificationMessage) GetImageURL() string {
	return s.ImageURL
}

// GetTitle returns the value of Title.
func (s *NotificationMessage) GetTitle() string {
	return s.Title
}

// SetBody sets the value of Body.
func (s *NotificationMessage) SetBody(val string) {
	s.Body = val
}

// SetColor sets the value of Color.
func (s *NotificationMessage) SetColor(val string) {
	s.Color = val
}

// SetColorCode sets the value of ColorCode.
func (s *NotificationMessage) SetColorCode(val string) {
	s.ColorCode = val
}

// SetIconURL sets the value of IconURL.
func (s *NotificationMessage) SetIconURL(val string) {
	s.IconURL = val
}

// SetImageURL sets the value of ImageURL.
func (s *NotificationMessage) SetImageURL(val string) {
	s.ImageURL = val
}

// SetTitle sets the value of Title.
func (s *NotificationMessage) SetTitle(val string) {
	s.Title = val
}

// Ref: #/components/schemas/NotificationStatus
type NotificationStatus struct {
	ID string `json:"id"`
	// - 0: 未送信
	// - 1: 送信中
	// - 2: 送信済
	// - 9: 送信失敗.
	Status                NotificationStatusStatus `json:"status"`
	ErrorInfo             string                   `json:"error_info"`
	NotificationRequestID string                   `json:"notification_request_id"`
	GroupID               string                   `json:"group_id"`
	DestinationID         string                   `json:"destination_id"`
	CreatedAt             time.Time                `json:"created_at"`
	UpdatedAt             time.Time                `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *NotificationStatus) GetID() string {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *NotificationStatus) GetStatus() NotificationStatusStatus {
	return s.Status
}

// GetErrorInfo returns the value of ErrorInfo.
func (s *NotificationStatus) GetErrorInfo() string {
	return s.ErrorInfo
}

// GetNotificationRequestID returns the value of NotificationRequestID.
func (s *NotificationStatus) GetNotificationRequestID() string {
	return s.NotificationRequestID
}

// GetGroupID returns the value of GroupID.
func (s *NotificationStatus) GetGroupID() string {
	return s.GroupID
}

// GetDestinationID returns the value of DestinationID.
func (s *NotificationStatus) GetDestinationID() string {
	return s.DestinationID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *NotificationStatus) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *NotificationStatus) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *NotificationStatus) SetID(val string) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *NotificationStatus) SetStatus(val NotificationStatusStatus) {
	s.Status = val
}

// SetErrorInfo sets the value of ErrorInfo.
func (s *NotificationStatus) SetErrorInfo(val string) {
	s.ErrorInfo = val
}

// SetNotificationRequestID sets the value of NotificationRequestID.
func (s *NotificationStatus) SetNotificationRequestID(val string) {
	s.NotificationRequestID = val
}

// SetGroupID sets the value of GroupID.
func (s *NotificationStatus) SetGroupID(val string) {
	s.GroupID = val
}

// SetDestinationID sets the value of DestinationID.
func (s *NotificationStatus) SetDestinationID(val string) {
	s.DestinationID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *NotificationStatus) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *NotificationStatus) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// - 0: 未送信
// - 1: 送信中
// - 2: 送信済
// - 9: 送信失敗.
type NotificationStatusStatus int

const (
	NotificationStatusStatus0 NotificationStatusStatus = 0
	NotificationStatusStatus1 NotificationStatusStatus = 1
	NotificationStatusStatus2 NotificationStatusStatus = 2
	NotificationStatusStatus9 NotificationStatusStatus = 9
)

// AllValues returns all NotificationStatusStatus values.
func (NotificationStatusStatus) AllValues() []NotificationStatusStatus {
	return []NotificationStatusStatus{
		NotificationStatusStatus0,
		NotificationStatusStatus1,
		NotificationStatusStatus2,
		NotificationStatusStatus9,
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPostCommonServiceItemRequest returns new OptPostCommonServiceItemRequest with value set to v.
func NewOptPostCommonServiceItemRequest(v PostCommonServiceItemRequest) OptPostCommonServiceItemRequest {
	return OptPostCommonServiceItemRequest{
		Value: v,
		Set:   true,
	}
}

// OptPostCommonServiceItemRequest is optional PostCommonServiceItemRequest.
type OptPostCommonServiceItemRequest struct {
	Value PostCommonServiceItemRequest
	Set   bool
}

// IsSet returns true if OptPostCommonServiceItemRequest was set.
func (o OptPostCommonServiceItemRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPostCommonServiceItemRequest) Reset() {
	var v PostCommonServiceItemRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPostCommonServiceItemRequest) SetTo(v PostCommonServiceItemRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPostCommonServiceItemRequest) Get() (v PostCommonServiceItemRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPostCommonServiceItemRequest) Or(d PostCommonServiceItemRequest) PostCommonServiceItemRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPutCommonServiceItemRequest returns new OptPutCommonServiceItemRequest with value set to v.
func NewOptPutCommonServiceItemRequest(v PutCommonServiceItemRequest) OptPutCommonServiceItemRequest {
	return OptPutCommonServiceItemRequest{
		Value: v,
		Set:   true,
	}
}

// OptPutCommonServiceItemRequest is optional PutCommonServiceItemRequest.
type OptPutCommonServiceItemRequest struct {
	Value PutCommonServiceItemRequest
	Set   bool
}

// IsSet returns true if OptPutCommonServiceItemRequest was set.
func (o OptPutCommonServiceItemRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPutCommonServiceItemRequest) Reset() {
	var v PutCommonServiceItemRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPutCommonServiceItemRequest) SetTo(v PutCommonServiceItemRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPutCommonServiceItemRequest) Get() (v PutCommonServiceItemRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPutCommonServiceItemRequest) Or(d PutCommonServiceItemRequest) PutCommonServiceItemRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPutCommonServiceItemRequestCommonServiceItemSettings returns new OptPutCommonServiceItemRequestCommonServiceItemSettings with value set to v.
func NewOptPutCommonServiceItemRequestCommonServiceItemSettings(v PutCommonServiceItemRequestCommonServiceItemSettings) OptPutCommonServiceItemRequestCommonServiceItemSettings {
	return OptPutCommonServiceItemRequestCommonServiceItemSettings{
		Value: v,
		Set:   true,
	}
}

// OptPutCommonServiceItemRequestCommonServiceItemSettings is optional PutCommonServiceItemRequestCommonServiceItemSettings.
type OptPutCommonServiceItemRequestCommonServiceItemSettings struct {
	Value PutCommonServiceItemRequestCommonServiceItemSettings
	Set   bool
}

// IsSet returns true if OptPutCommonServiceItemRequestCommonServiceItemSettings was set.
func (o OptPutCommonServiceItemRequestCommonServiceItemSettings) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPutCommonServiceItemRequestCommonServiceItemSettings) Reset() {
	var v PutCommonServiceItemRequestCommonServiceItemSettings
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPutCommonServiceItemRequestCommonServiceItemSettings) SetTo(v PutCommonServiceItemRequestCommonServiceItemSettings) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPutCommonServiceItemRequestCommonServiceItemSettings) Get() (v PutCommonServiceItemRequestCommonServiceItemSettings, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPutCommonServiceItemRequestCommonServiceItemSettings) Or(d PutCommonServiceItemRequestCommonServiceItemSettings) PutCommonServiceItemRequestCommonServiceItemSettings {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPutCommonServiceItemRoutingReorderRequest returns new OptPutCommonServiceItemRoutingReorderRequest with value set to v.
func NewOptPutCommonServiceItemRoutingReorderRequest(v PutCommonServiceItemRoutingReorderRequest) OptPutCommonServiceItemRoutingReorderRequest {
	return OptPutCommonServiceItemRoutingReorderRequest{
		Value: v,
		Set:   true,
	}
}

// OptPutCommonServiceItemRoutingReorderRequest is optional PutCommonServiceItemRoutingReorderRequest.
type OptPutCommonServiceItemRoutingReorderRequest struct {
	Value PutCommonServiceItemRoutingReorderRequest
	Set   bool
}

// IsSet returns true if OptPutCommonServiceItemRoutingReorderRequest was set.
func (o OptPutCommonServiceItemRoutingReorderRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPutCommonServiceItemRoutingReorderRequest) Reset() {
	var v PutCommonServiceItemRoutingReorderRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPutCommonServiceItemRoutingReorderRequest) SetTo(v PutCommonServiceItemRoutingReorderRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPutCommonServiceItemRoutingReorderRequest) Get() (v PutCommonServiceItemRoutingReorderRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPutCommonServiceItemRoutingReorderRequest) Or(d PutCommonServiceItemRoutingReorderRequest) PutCommonServiceItemRoutingReorderRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSendNotificationMessageRequest returns new OptSendNotificationMessageRequest with value set to v.
func NewOptSendNotificationMessageRequest(v SendNotificationMessageRequest) OptSendNotificationMessageRequest {
	return OptSendNotificationMessageRequest{
		Value: v,
		Set:   true,
	}
}

// OptSendNotificationMessageRequest is optional SendNotificationMessageRequest.
type OptSendNotificationMessageRequest struct {
	Value SendNotificationMessageRequest
	Set   bool
}

// IsSet returns true if OptSendNotificationMessageRequest was set.
func (o OptSendNotificationMessageRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSendNotificationMessageRequest) Reset() {
	var v SendNotificationMessageRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSendNotificationMessageRequest) SetTo(v SendNotificationMessageRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSendNotificationMessageRequest) Get() (v SendNotificationMessageRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSendNotificationMessageRequest) Or(d SendNotificationMessageRequest) SendNotificationMessageRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PostCommonServiceItemRequest
type PostCommonServiceItemRequest struct {
	CommonServiceItem PostCommonServiceItemRequestCommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *PostCommonServiceItemRequest) GetCommonServiceItem() PostCommonServiceItemRequestCommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *PostCommonServiceItemRequest) SetCommonServiceItem(val PostCommonServiceItemRequestCommonServiceItem) {
	s.CommonServiceItem = val
}

type PostCommonServiceItemRequestCommonServiceItem struct {
	Name         string                                                `json:"Name"`
	Description  string                                                `json:"Description"`
	Tags         []string                                              `json:"Tags"`
	Icon         PostCommonServiceItemRequestCommonServiceItemIcon     `json:"Icon"`
	ServiceClass OptString                                             `json:"ServiceClass"`
	Provider     PostCommonServiceItemRequestCommonServiceItemProvider `json:"Provider"`
	Settings     PostCommonServiceItemRequestCommonServiceItemSettings `json:"Settings"`
}

// GetName returns the value of Name.
func (s *PostCommonServiceItemRequestCommonServiceItem) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *PostCommonServiceItemRequestCommonServiceItem) GetDescription() string {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *PostCommonServiceItemRequestCommonServiceItem) GetTags() []string {
	return s.Tags
}

// GetIcon returns the value of Icon.
func (s *PostCommonServiceItemRequestCommonServiceItem) GetIcon() PostCommonServiceItemRequestCommonServiceItemIcon {
	return s.Icon
}

// GetServiceClass returns the value of ServiceClass.
func (s *PostCommonServiceItemRequestCommonServiceItem) GetServiceClass() OptString {
	return s.ServiceClass
}

// GetProvider returns the value of Provider.
func (s *PostCommonServiceItemRequestCommonServiceItem) GetProvider() PostCommonServiceItemRequestCommonServiceItemProvider {
	return s.Provider
}

// GetSettings returns the value of Settings.
func (s *PostCommonServiceItemRequestCommonServiceItem) GetSettings() PostCommonServiceItemRequestCommonServiceItemSettings {
	return s.Settings
}

// SetName sets the value of Name.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetDescription(val string) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetTags(val []string) {
	s.Tags = val
}

// SetIcon sets the value of Icon.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetIcon(val PostCommonServiceItemRequestCommonServiceItemIcon) {
	s.Icon = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetServiceClass(val OptString) {
	s.ServiceClass = val
}

// SetProvider sets the value of Provider.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetProvider(val PostCommonServiceItemRequestCommonServiceItemProvider) {
	s.Provider = val
}

// SetSettings sets the value of Settings.
func (s *PostCommonServiceItemRequestCommonServiceItem) SetSettings(val PostCommonServiceItemRequestCommonServiceItemSettings) {
	s.Settings = val
}

type PostCommonServiceItemRequestCommonServiceItemIcon struct{}

type PostCommonServiceItemRequestCommonServiceItemProvider struct {
	Class        PostCommonServiceItemRequestCommonServiceItemProviderClass `json:"Class"`
	Name         OptString                                                  `json:"Name"`
	ServiceClass OptString                                                  `json:"ServiceClass"`
}

// GetClass returns the value of Class.
func (s *PostCommonServiceItemRequestCommonServiceItemProvider) GetClass() PostCommonServiceItemRequestCommonServiceItemProviderClass {
	return s.Class
}

// GetName returns the value of Name.
func (s *PostCommonServiceItemRequestCommonServiceItemProvider) GetName() OptString {
	return s.Name
}

// GetServiceClass returns the value of ServiceClass.
func (s *PostCommonServiceItemRequestCommonServiceItemProvider) GetServiceClass() OptString {
	return s.ServiceClass
}

// SetClass sets the value of Class.
func (s *PostCommonServiceItemRequestCommonServiceItemProvider) SetClass(val PostCommonServiceItemRequestCommonServiceItemProviderClass) {
	s.Class = val
}

// SetName sets the value of Name.
func (s *PostCommonServiceItemRequestCommonServiceItemProvider) SetName(val OptString) {
	s.Name = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *PostCommonServiceItemRequestCommonServiceItemProvider) SetServiceClass(val OptString) {
	s.ServiceClass = val
}

type PostCommonServiceItemRequestCommonServiceItemProviderClass string

const (
	PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticedestination PostCommonServiceItemRequestCommonServiceItemProviderClass = "saknoticedestination"
	PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticegroup       PostCommonServiceItemRequestCommonServiceItemProviderClass = "saknoticegroup"
	PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticerouting     PostCommonServiceItemRequestCommonServiceItemProviderClass = "saknoticerouting"
)

// AllValues returns all PostCommonServiceItemRequestCommonServiceItemProviderClass values.
func (PostCommonServiceItemRequestCommonServiceItemProviderClass) AllValues() []PostCommonServiceItemRequestCommonServiceItemProviderClass {
	return []PostCommonServiceItemRequestCommonServiceItemProviderClass{
		PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticedestination,
		PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticegroup,
		PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticerouting,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PostCommonServiceItemRequestCommonServiceItemProviderClass) MarshalText() ([]byte, error) {
	switch s {
	case PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticedestination:
		return []byte(s), nil
	case PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticegroup:
		return []byte(s), nil
	case PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticerouting:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PostCommonServiceItemRequestCommonServiceItemProviderClass) UnmarshalText(data []byte) error {
	switch PostCommonServiceItemRequestCommonServiceItemProviderClass(data) {
	case PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticedestination:
		*s = PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticedestination
		return nil
	case PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticegroup:
		*s = PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticegroup
		return nil
	case PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticerouting:
		*s = PostCommonServiceItemRequestCommonServiceItemProviderClassSaknoticerouting
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// PostCommonServiceItemRequestCommonServiceItemSettings represents sum type.
type PostCommonServiceItemRequestCommonServiceItemSettings struct {
	Type                                 PostCommonServiceItemRequestCommonServiceItemSettingsType // switch on this field
	CommonServiceItemDestinationSettings CommonServiceItemDestinationSettings
	CommonServiceItemGroupSettings       CommonServiceItemGroupSettings
	CommonServiceItemRoutingSettings     CommonServiceItemRoutingSettings
}

// PostCommonServiceItemRequestCommonServiceItemSettingsType is oneOf type of PostCommonServiceItemRequestCommonServiceItemSettings.
type PostCommonServiceItemRequestCommonServiceItemSettingsType string

// Possible values for PostCommonServiceItemRequestCommonServiceItemSettingsType.
const (
	CommonServiceItemDestinationSettingsPostCommonServiceItemRequestCommonServiceItemSettings PostCommonServiceItemRequestCommonServiceItemSettingsType = "CommonServiceItemDestinationSettings"
	CommonServiceItemGroupSettingsPostCommonServiceItemRequestCommonServiceItemSettings       PostCommonServiceItemRequestCommonServiceItemSettingsType = "CommonServiceItemGroupSettings"
	CommonServiceItemRoutingSettingsPostCommonServiceItemRequestCommonServiceItemSettings     PostCommonServiceItemRequestCommonServiceItemSettingsType = "CommonServiceItemRoutingSettings"
)

// IsCommonServiceItemDestinationSettings reports whether PostCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemDestinationSettings.
func (s PostCommonServiceItemRequestCommonServiceItemSettings) IsCommonServiceItemDestinationSettings() bool {
	return s.Type == CommonServiceItemDestinationSettingsPostCommonServiceItemRequestCommonServiceItemSettings
}

// IsCommonServiceItemGroupSettings reports whether PostCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemGroupSettings.
func (s PostCommonServiceItemRequestCommonServiceItemSettings) IsCommonServiceItemGroupSettings() bool {
	return s.Type == CommonServiceItemGroupSettingsPostCommonServiceItemRequestCommonServiceItemSettings
}

// IsCommonServiceItemRoutingSettings reports whether PostCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemRoutingSettings.
func (s PostCommonServiceItemRequestCommonServiceItemSettings) IsCommonServiceItemRoutingSettings() bool {
	return s.Type == CommonServiceItemRoutingSettingsPostCommonServiceItemRequestCommonServiceItemSettings
}

// SetCommonServiceItemDestinationSettings sets PostCommonServiceItemRequestCommonServiceItemSettings to CommonServiceItemDestinationSettings.
func (s *PostCommonServiceItemRequestCommonServiceItemSettings) SetCommonServiceItemDestinationSettings(v CommonServiceItemDestinationSettings) {
	s.Type = CommonServiceItemDestinationSettingsPostCommonServiceItemRequestCommonServiceItemSettings
	s.CommonServiceItemDestinationSettings = v
}

// GetCommonServiceItemDestinationSettings returns CommonServiceItemDestinationSettings and true boolean if PostCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemDestinationSettings.
func (s PostCommonServiceItemRequestCommonServiceItemSettings) GetCommonServiceItemDestinationSettings() (v CommonServiceItemDestinationSettings, ok bool) {
	if !s.IsCommonServiceItemDestinationSettings() {
		return v, false
	}
	return s.CommonServiceItemDestinationSettings, true
}

// NewCommonServiceItemDestinationSettingsPostCommonServiceItemRequestCommonServiceItemSettings returns new PostCommonServiceItemRequestCommonServiceItemSettings from CommonServiceItemDestinationSettings.
func NewCommonServiceItemDestinationSettingsPostCommonServiceItemRequestCommonServiceItemSettings(v CommonServiceItemDestinationSettings) PostCommonServiceItemRequestCommonServiceItemSettings {
	var s PostCommonServiceItemRequestCommonServiceItemSettings
	s.SetCommonServiceItemDestinationSettings(v)
	return s
}

// SetCommonServiceItemGroupSettings sets PostCommonServiceItemRequestCommonServiceItemSettings to CommonServiceItemGroupSettings.
func (s *PostCommonServiceItemRequestCommonServiceItemSettings) SetCommonServiceItemGroupSettings(v CommonServiceItemGroupSettings) {
	s.Type = CommonServiceItemGroupSettingsPostCommonServiceItemRequestCommonServiceItemSettings
	s.CommonServiceItemGroupSettings = v
}

// GetCommonServiceItemGroupSettings returns CommonServiceItemGroupSettings and true boolean if PostCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemGroupSettings.
func (s PostCommonServiceItemRequestCommonServiceItemSettings) GetCommonServiceItemGroupSettings() (v CommonServiceItemGroupSettings, ok bool) {
	if !s.IsCommonServiceItemGroupSettings() {
		return v, false
	}
	return s.CommonServiceItemGroupSettings, true
}

// NewCommonServiceItemGroupSettingsPostCommonServiceItemRequestCommonServiceItemSettings returns new PostCommonServiceItemRequestCommonServiceItemSettings from CommonServiceItemGroupSettings.
func NewCommonServiceItemGroupSettingsPostCommonServiceItemRequestCommonServiceItemSettings(v CommonServiceItemGroupSettings) PostCommonServiceItemRequestCommonServiceItemSettings {
	var s PostCommonServiceItemRequestCommonServiceItemSettings
	s.SetCommonServiceItemGroupSettings(v)
	return s
}

// SetCommonServiceItemRoutingSettings sets PostCommonServiceItemRequestCommonServiceItemSettings to CommonServiceItemRoutingSettings.
func (s *PostCommonServiceItemRequestCommonServiceItemSettings) SetCommonServiceItemRoutingSettings(v CommonServiceItemRoutingSettings) {
	s.Type = CommonServiceItemRoutingSettingsPostCommonServiceItemRequestCommonServiceItemSettings
	s.CommonServiceItemRoutingSettings = v
}

// GetCommonServiceItemRoutingSettings returns CommonServiceItemRoutingSettings and true boolean if PostCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemRoutingSettings.
func (s PostCommonServiceItemRequestCommonServiceItemSettings) GetCommonServiceItemRoutingSettings() (v CommonServiceItemRoutingSettings, ok bool) {
	if !s.IsCommonServiceItemRoutingSettings() {
		return v, false
	}
	return s.CommonServiceItemRoutingSettings, true
}

// NewCommonServiceItemRoutingSettingsPostCommonServiceItemRequestCommonServiceItemSettings returns new PostCommonServiceItemRequestCommonServiceItemSettings from CommonServiceItemRoutingSettings.
func NewCommonServiceItemRoutingSettingsPostCommonServiceItemRequestCommonServiceItemSettings(v CommonServiceItemRoutingSettings) PostCommonServiceItemRequestCommonServiceItemSettings {
	var s PostCommonServiceItemRequestCommonServiceItemSettings
	s.SetCommonServiceItemRoutingSettings(v)
	return s
}

// Ref: #/components/schemas/PutCommonServiceItemRequest
type PutCommonServiceItemRequest struct {
	CommonServiceItem PutCommonServiceItemRequestCommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *PutCommonServiceItemRequest) GetCommonServiceItem() PutCommonServiceItemRequestCommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *PutCommonServiceItemRequest) SetCommonServiceItem(val PutCommonServiceItemRequestCommonServiceItem) {
	s.CommonServiceItem = val
}

type PutCommonServiceItemRequestCommonServiceItem struct {
	Name        string                                                  `json:"Name"`
	Description string                                                  `json:"Description"`
	Tags        []string                                                `json:"Tags"`
	Icon        PutCommonServiceItemRequestCommonServiceItemIcon        `json:"Icon"`
	Settings    OptPutCommonServiceItemRequestCommonServiceItemSettings `json:"Settings"`
}

// GetName returns the value of Name.
func (s *PutCommonServiceItemRequestCommonServiceItem) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *PutCommonServiceItemRequestCommonServiceItem) GetDescription() string {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *PutCommonServiceItemRequestCommonServiceItem) GetTags() []string {
	return s.Tags
}

// GetIcon returns the value of Icon.
func (s *PutCommonServiceItemRequestCommonServiceItem) GetIcon() PutCommonServiceItemRequestCommonServiceItemIcon {
	return s.Icon
}

// GetSettings returns the value of Settings.
func (s *PutCommonServiceItemRequestCommonServiceItem) GetSettings() OptPutCommonServiceItemRequestCommonServiceItemSettings {
	return s.Settings
}

// SetName sets the value of Name.
func (s *PutCommonServiceItemRequestCommonServiceItem) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *PutCommonServiceItemRequestCommonServiceItem) SetDescription(val string) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *PutCommonServiceItemRequestCommonServiceItem) SetTags(val []string) {
	s.Tags = val
}

// SetIcon sets the value of Icon.
func (s *PutCommonServiceItemRequestCommonServiceItem) SetIcon(val PutCommonServiceItemRequestCommonServiceItemIcon) {
	s.Icon = val
}

// SetSettings sets the value of Settings.
func (s *PutCommonServiceItemRequestCommonServiceItem) SetSettings(val OptPutCommonServiceItemRequestCommonServiceItemSettings) {
	s.Settings = val
}

type PutCommonServiceItemRequestCommonServiceItemIcon struct{}

// PutCommonServiceItemRequestCommonServiceItemSettings represents sum type.
type PutCommonServiceItemRequestCommonServiceItemSettings struct {
	Type                                 PutCommonServiceItemRequestCommonServiceItemSettingsType // switch on this field
	CommonServiceItemDestinationSettings CommonServiceItemDestinationSettings
	CommonServiceItemGroupSettings       CommonServiceItemGroupSettings
	CommonServiceItemRoutingSettings     CommonServiceItemRoutingSettings
}

// PutCommonServiceItemRequestCommonServiceItemSettingsType is oneOf type of PutCommonServiceItemRequestCommonServiceItemSettings.
type PutCommonServiceItemRequestCommonServiceItemSettingsType string

// Possible values for PutCommonServiceItemRequestCommonServiceItemSettingsType.
const (
	CommonServiceItemDestinationSettingsPutCommonServiceItemRequestCommonServiceItemSettings PutCommonServiceItemRequestCommonServiceItemSettingsType = "CommonServiceItemDestinationSettings"
	CommonServiceItemGroupSettingsPutCommonServiceItemRequestCommonServiceItemSettings       PutCommonServiceItemRequestCommonServiceItemSettingsType = "CommonServiceItemGroupSettings"
	CommonServiceItemRoutingSettingsPutCommonServiceItemRequestCommonServiceItemSettings     PutCommonServiceItemRequestCommonServiceItemSettingsType = "CommonServiceItemRoutingSettings"
)

// IsCommonServiceItemDestinationSettings reports whether PutCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemDestinationSettings.
func (s PutCommonServiceItemRequestCommonServiceItemSettings) IsCommonServiceItemDestinationSettings() bool {
	return s.Type == CommonServiceItemDestinationSettingsPutCommonServiceItemRequestCommonServiceItemSettings
}

// IsCommonServiceItemGroupSettings reports whether PutCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemGroupSettings.
func (s PutCommonServiceItemRequestCommonServiceItemSettings) IsCommonServiceItemGroupSettings() bool {
	return s.Type == CommonServiceItemGroupSettingsPutCommonServiceItemRequestCommonServiceItemSettings
}

// IsCommonServiceItemRoutingSettings reports whether PutCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemRoutingSettings.
func (s PutCommonServiceItemRequestCommonServiceItemSettings) IsCommonServiceItemRoutingSettings() bool {
	return s.Type == CommonServiceItemRoutingSettingsPutCommonServiceItemRequestCommonServiceItemSettings
}

// SetCommonServiceItemDestinationSettings sets PutCommonServiceItemRequestCommonServiceItemSettings to CommonServiceItemDestinationSettings.
func (s *PutCommonServiceItemRequestCommonServiceItemSettings) SetCommonServiceItemDestinationSettings(v CommonServiceItemDestinationSettings) {
	s.Type = CommonServiceItemDestinationSettingsPutCommonServiceItemRequestCommonServiceItemSettings
	s.CommonServiceItemDestinationSettings = v
}

// GetCommonServiceItemDestinationSettings returns CommonServiceItemDestinationSettings and true boolean if PutCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemDestinationSettings.
func (s PutCommonServiceItemRequestCommonServiceItemSettings) GetCommonServiceItemDestinationSettings() (v CommonServiceItemDestinationSettings, ok bool) {
	if !s.IsCommonServiceItemDestinationSettings() {
		return v, false
	}
	return s.CommonServiceItemDestinationSettings, true
}

// NewCommonServiceItemDestinationSettingsPutCommonServiceItemRequestCommonServiceItemSettings returns new PutCommonServiceItemRequestCommonServiceItemSettings from CommonServiceItemDestinationSettings.
func NewCommonServiceItemDestinationSettingsPutCommonServiceItemRequestCommonServiceItemSettings(v CommonServiceItemDestinationSettings) PutCommonServiceItemRequestCommonServiceItemSettings {
	var s PutCommonServiceItemRequestCommonServiceItemSettings
	s.SetCommonServiceItemDestinationSettings(v)
	return s
}

// SetCommonServiceItemGroupSettings sets PutCommonServiceItemRequestCommonServiceItemSettings to CommonServiceItemGroupSettings.
func (s *PutCommonServiceItemRequestCommonServiceItemSettings) SetCommonServiceItemGroupSettings(v CommonServiceItemGroupSettings) {
	s.Type = CommonServiceItemGroupSettingsPutCommonServiceItemRequestCommonServiceItemSettings
	s.CommonServiceItemGroupSettings = v
}

// GetCommonServiceItemGroupSettings returns CommonServiceItemGroupSettings and true boolean if PutCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemGroupSettings.
func (s PutCommonServiceItemRequestCommonServiceItemSettings) GetCommonServiceItemGroupSettings() (v CommonServiceItemGroupSettings, ok bool) {
	if !s.IsCommonServiceItemGroupSettings() {
		return v, false
	}
	return s.CommonServiceItemGroupSettings, true
}

// NewCommonServiceItemGroupSettingsPutCommonServiceItemRequestCommonServiceItemSettings returns new PutCommonServiceItemRequestCommonServiceItemSettings from CommonServiceItemGroupSettings.
func NewCommonServiceItemGroupSettingsPutCommonServiceItemRequestCommonServiceItemSettings(v CommonServiceItemGroupSettings) PutCommonServiceItemRequestCommonServiceItemSettings {
	var s PutCommonServiceItemRequestCommonServiceItemSettings
	s.SetCommonServiceItemGroupSettings(v)
	return s
}

// SetCommonServiceItemRoutingSettings sets PutCommonServiceItemRequestCommonServiceItemSettings to CommonServiceItemRoutingSettings.
func (s *PutCommonServiceItemRequestCommonServiceItemSettings) SetCommonServiceItemRoutingSettings(v CommonServiceItemRoutingSettings) {
	s.Type = CommonServiceItemRoutingSettingsPutCommonServiceItemRequestCommonServiceItemSettings
	s.CommonServiceItemRoutingSettings = v
}

// GetCommonServiceItemRoutingSettings returns CommonServiceItemRoutingSettings and true boolean if PutCommonServiceItemRequestCommonServiceItemSettings is CommonServiceItemRoutingSettings.
func (s PutCommonServiceItemRequestCommonServiceItemSettings) GetCommonServiceItemRoutingSettings() (v CommonServiceItemRoutingSettings, ok bool) {
	if !s.IsCommonServiceItemRoutingSettings() {
		return v, false
	}
	return s.CommonServiceItemRoutingSettings, true
}

// NewCommonServiceItemRoutingSettingsPutCommonServiceItemRequestCommonServiceItemSettings returns new PutCommonServiceItemRequestCommonServiceItemSettings from CommonServiceItemRoutingSettings.
func NewCommonServiceItemRoutingSettingsPutCommonServiceItemRequestCommonServiceItemSettings(v CommonServiceItemRoutingSettings) PutCommonServiceItemRequestCommonServiceItemSettings {
	var s PutCommonServiceItemRequestCommonServiceItemSettings
	s.SetCommonServiceItemRoutingSettings(v)
	return s
}

// Ref: #/components/schemas/PutCommonServiceItemRoutingReorderRequest
type PutCommonServiceItemRoutingReorderRequest struct {
	Orders []PutCommonServiceItemRoutingReorderRequestOrdersItem `json:"Orders"`
}

// GetOrders returns the value of Orders.
func (s *PutCommonServiceItemRoutingReorderRequest) GetOrders() []PutCommonServiceItemRoutingReorderRequestOrdersItem {
	return s.Orders
}

// SetOrders sets the value of Orders.
func (s *PutCommonServiceItemRoutingReorderRequest) SetOrders(val []PutCommonServiceItemRoutingReorderRequestOrdersItem) {
	s.Orders = val
}

type PutCommonServiceItemRoutingReorderRequestOrdersItem struct {
	PriorityRank int    `json:"PriorityRank"`
	RoutingID    string `json:"RoutingID"`
}

// GetPriorityRank returns the value of PriorityRank.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) GetPriorityRank() int {
	return s.PriorityRank
}

// GetRoutingID returns the value of RoutingID.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) GetRoutingID() string {
	return s.RoutingID
}

// SetPriorityRank sets the value of PriorityRank.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) SetPriorityRank(val int) {
	s.PriorityRank = val
}

// SetRoutingID sets the value of RoutingID.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) SetRoutingID(val string) {
	s.RoutingID = val
}

type ReorderRoutingAccepted struct {
	IsOk OptBool `json:"is_ok"`
}

// GetIsOk returns the value of IsOk.
func (s *ReorderRoutingAccepted) GetIsOk() OptBool {
	return s.IsOk
}

// SetIsOk sets the value of IsOk.
func (s *ReorderRoutingAccepted) SetIsOk(val OptBool) {
	s.IsOk = val
}

// Ref: #/components/schemas/SendNotificationMessageRequest
type SendNotificationMessageRequest struct {
	Message string `json:"Message"`
}

// GetMessage returns the value of Message.
func (s *SendNotificationMessageRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *SendNotificationMessageRequest) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/SendNotificationMessageResponse
type SendNotificationMessageResponse struct {
	IsOk bool `json:"is_ok"`
}

// GetIsOk returns the value of IsOk.
func (s *SendNotificationMessageResponse) GetIsOk() bool {
	return s.IsOk
}

// SetIsOk sets the value of IsOk.
func (s *SendNotificationMessageResponse) SetIsOk(val bool) {
	s.IsOk = val
}

type UpdateCommonServiceItemOK struct {
	CommonServiceItem CommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *UpdateCommonServiceItemOK) GetCommonServiceItem() CommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *UpdateCommonServiceItemOK) SetCommonServiceItem(val CommonServiceItem) {
	s.CommonServiceItem = val
}
