// Code generated by ogen, DO NOT EDIT.

package v1

// DeleteCommonServiceItemParams is parameters of deleteCommonServiceItem operation.
type DeleteCommonServiceItemParams struct {
	ID string
}

// GetCommonServiceItemParams is parameters of getCommonServiceItem operation.
type GetCommonServiceItemParams struct {
	ID string
}

// GetCommonServiceItemStatusParams is parameters of getCommonServiceItemStatus operation.
type GetCommonServiceItemStatusParams struct {
	ID string
}

// GetNotificationHistoryParams is parameters of getNotificationHistory operation.
type GetNotificationHistoryParams struct {
	RequestID string
}

// SendNotificationMessageParams is parameters of sendNotificationMessage operation.
type SendNotificationMessageParams struct {
	ID string
}

// UpdateCommonServiceItemParams is parameters of updateCommonServiceItem operation.
type UpdateCommonServiceItemParams struct {
	ID string
}
