// Copyright 2022-2025 The sacloud/simple-notification-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/CommonServiceItemRouting
type CommonServiceItemRouting struct {
	CommonServiceItem CommonServiceItemRoutingCommonServiceItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *CommonServiceItemRouting) GetCommonServiceItem() CommonServiceItemRoutingCommonServiceItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *CommonServiceItemRouting) SetCommonServiceItem(val CommonServiceItemRoutingCommonServiceItem) {
	s.CommonServiceItem = val
}

type CommonServiceItemRoutingCommonServiceItem struct {
	ID           string                           `json:"ID"`
	Name         OptNilString                     `json:"Name"`
	Description  OptNilString                     `json:"Description"`
	ServiceClass NilString                        `json:"ServiceClass"`
	Provider     Provider                         `json:"Provider"`
	Settings     CommonServiceItemRoutingSettings `json:"Settings"`
}

// GetID returns the value of ID.
func (s *CommonServiceItemRoutingCommonServiceItem) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *CommonServiceItemRoutingCommonServiceItem) GetName() OptNilString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CommonServiceItemRoutingCommonServiceItem) GetDescription() OptNilString {
	return s.Description
}

// GetServiceClass returns the value of ServiceClass.
func (s *CommonServiceItemRoutingCommonServiceItem) GetServiceClass() NilString {
	return s.ServiceClass
}

// GetProvider returns the value of Provider.
func (s *CommonServiceItemRoutingCommonServiceItem) GetProvider() Provider {
	return s.Provider
}

// GetSettings returns the value of Settings.
func (s *CommonServiceItemRoutingCommonServiceItem) GetSettings() CommonServiceItemRoutingSettings {
	return s.Settings
}

// SetID sets the value of ID.
func (s *CommonServiceItemRoutingCommonServiceItem) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *CommonServiceItemRoutingCommonServiceItem) SetName(val OptNilString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CommonServiceItemRoutingCommonServiceItem) SetDescription(val OptNilString) {
	s.Description = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *CommonServiceItemRoutingCommonServiceItem) SetServiceClass(val NilString) {
	s.ServiceClass = val
}

// SetProvider sets the value of Provider.
func (s *CommonServiceItemRoutingCommonServiceItem) SetProvider(val Provider) {
	s.Provider = val
}

// SetSettings sets the value of Settings.
func (s *CommonServiceItemRoutingCommonServiceItem) SetSettings(val CommonServiceItemRoutingSettings) {
	s.Settings = val
}

// Ref: #/components/schemas/CommonServiceItemRoutingSettings
type CommonServiceItemRoutingSettings struct {
	SourceID      string                                            `json:"SourceID"`
	MatchLabels   []CommonServiceItemRoutingSettingsMatchLabelsItem `json:"MatchLabels"`
	TargetGroupID string                                            `json:"TargetGroupID"`
	PriorityRank  int                                               `json:"PriorityRank"`
}

// GetSourceID returns the value of SourceID.
func (s *CommonServiceItemRoutingSettings) GetSourceID() string {
	return s.SourceID
}

// GetMatchLabels returns the value of MatchLabels.
func (s *CommonServiceItemRoutingSettings) GetMatchLabels() []CommonServiceItemRoutingSettingsMatchLabelsItem {
	return s.MatchLabels
}

// GetTargetGroupID returns the value of TargetGroupID.
func (s *CommonServiceItemRoutingSettings) GetTargetGroupID() string {
	return s.TargetGroupID
}

// GetPriorityRank returns the value of PriorityRank.
func (s *CommonServiceItemRoutingSettings) GetPriorityRank() int {
	return s.PriorityRank
}

// SetSourceID sets the value of SourceID.
func (s *CommonServiceItemRoutingSettings) SetSourceID(val string) {
	s.SourceID = val
}

// SetMatchLabels sets the value of MatchLabels.
func (s *CommonServiceItemRoutingSettings) SetMatchLabels(val []CommonServiceItemRoutingSettingsMatchLabelsItem) {
	s.MatchLabels = val
}

// SetTargetGroupID sets the value of TargetGroupID.
func (s *CommonServiceItemRoutingSettings) SetTargetGroupID(val string) {
	s.TargetGroupID = val
}

// SetPriorityRank sets the value of PriorityRank.
func (s *CommonServiceItemRoutingSettings) SetPriorityRank(val int) {
	s.PriorityRank = val
}

type CommonServiceItemRoutingSettingsMatchLabelsItem struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
}

// GetName returns the value of Name.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) SetValue(val string) {
	s.Value = val
}

// Ref: #/components/schemas/Error
type Error struct {
	IsFatal   OptBool   `json:"is_fatal"`
	Serial    OptString `json:"serial"`
	Status    OptString `json:"status"`
	ErrorCode OptString `json:"error_code"`
	ErrorMsg  OptString `json:"error_msg"`
}

// GetIsFatal returns the value of IsFatal.
func (s *Error) GetIsFatal() OptBool {
	return s.IsFatal
}

// GetSerial returns the value of Serial.
func (s *Error) GetSerial() OptString {
	return s.Serial
}

// GetStatus returns the value of Status.
func (s *Error) GetStatus() OptString {
	return s.Status
}

// GetErrorCode returns the value of ErrorCode.
func (s *Error) GetErrorCode() OptString {
	return s.ErrorCode
}

// GetErrorMsg returns the value of ErrorMsg.
func (s *Error) GetErrorMsg() OptString {
	return s.ErrorMsg
}

// SetIsFatal sets the value of IsFatal.
func (s *Error) SetIsFatal(val OptBool) {
	s.IsFatal = val
}

// SetSerial sets the value of Serial.
func (s *Error) SetSerial(val OptString) {
	s.Serial = val
}

// SetStatus sets the value of Status.
func (s *Error) SetStatus(val OptString) {
	s.Status = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *Error) SetErrorCode(val OptString) {
	s.ErrorCode = val
}

// SetErrorMsg sets the value of ErrorMsg.
func (s *Error) SetErrorMsg(val OptString) {
	s.ErrorMsg = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPostCommonServiceItemRoutingRequest returns new OptPostCommonServiceItemRoutingRequest with value set to v.
func NewOptPostCommonServiceItemRoutingRequest(v PostCommonServiceItemRoutingRequest) OptPostCommonServiceItemRoutingRequest {
	return OptPostCommonServiceItemRoutingRequest{
		Value: v,
		Set:   true,
	}
}

// OptPostCommonServiceItemRoutingRequest is optional PostCommonServiceItemRoutingRequest.
type OptPostCommonServiceItemRoutingRequest struct {
	Value PostCommonServiceItemRoutingRequest
	Set   bool
}

// IsSet returns true if OptPostCommonServiceItemRoutingRequest was set.
func (o OptPostCommonServiceItemRoutingRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPostCommonServiceItemRoutingRequest) Reset() {
	var v PostCommonServiceItemRoutingRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPostCommonServiceItemRoutingRequest) SetTo(v PostCommonServiceItemRoutingRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPostCommonServiceItemRoutingRequest) Get() (v PostCommonServiceItemRoutingRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPostCommonServiceItemRoutingRequest) Or(d PostCommonServiceItemRoutingRequest) PostCommonServiceItemRoutingRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPutCommonServiceItemRoutingReorderRequest returns new OptPutCommonServiceItemRoutingReorderRequest with value set to v.
func NewOptPutCommonServiceItemRoutingReorderRequest(v PutCommonServiceItemRoutingReorderRequest) OptPutCommonServiceItemRoutingReorderRequest {
	return OptPutCommonServiceItemRoutingReorderRequest{
		Value: v,
		Set:   true,
	}
}

// OptPutCommonServiceItemRoutingReorderRequest is optional PutCommonServiceItemRoutingReorderRequest.
type OptPutCommonServiceItemRoutingReorderRequest struct {
	Value PutCommonServiceItemRoutingReorderRequest
	Set   bool
}

// IsSet returns true if OptPutCommonServiceItemRoutingReorderRequest was set.
func (o OptPutCommonServiceItemRoutingReorderRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPutCommonServiceItemRoutingReorderRequest) Reset() {
	var v PutCommonServiceItemRoutingReorderRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPutCommonServiceItemRoutingReorderRequest) SetTo(v PutCommonServiceItemRoutingReorderRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPutCommonServiceItemRoutingReorderRequest) Get() (v PutCommonServiceItemRoutingReorderRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPutCommonServiceItemRoutingReorderRequest) Or(d PutCommonServiceItemRoutingReorderRequest) PutCommonServiceItemRoutingReorderRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPutCommonServiceItemRoutingRequest returns new OptPutCommonServiceItemRoutingRequest with value set to v.
func NewOptPutCommonServiceItemRoutingRequest(v PutCommonServiceItemRoutingRequest) OptPutCommonServiceItemRoutingRequest {
	return OptPutCommonServiceItemRoutingRequest{
		Value: v,
		Set:   true,
	}
}

// OptPutCommonServiceItemRoutingRequest is optional PutCommonServiceItemRoutingRequest.
type OptPutCommonServiceItemRoutingRequest struct {
	Value PutCommonServiceItemRoutingRequest
	Set   bool
}

// IsSet returns true if OptPutCommonServiceItemRoutingRequest was set.
func (o OptPutCommonServiceItemRoutingRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPutCommonServiceItemRoutingRequest) Reset() {
	var v PutCommonServiceItemRoutingRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPutCommonServiceItemRoutingRequest) SetTo(v PutCommonServiceItemRoutingRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPutCommonServiceItemRoutingRequest) Get() (v PutCommonServiceItemRoutingRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPutCommonServiceItemRoutingRequest) Or(d PutCommonServiceItemRoutingRequest) PutCommonServiceItemRoutingRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PostCommonServiceItemRoutingRequest
type PostCommonServiceItemRoutingRequest struct {
	CommonServiceItem PostCommonServiceItemRoutingRequestItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *PostCommonServiceItemRoutingRequest) GetCommonServiceItem() PostCommonServiceItemRoutingRequestItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *PostCommonServiceItemRoutingRequest) SetCommonServiceItem(val PostCommonServiceItemRoutingRequestItem) {
	s.CommonServiceItem = val
}

// Ref: #/components/schemas/PostCommonServiceItemRoutingRequestItem
type PostCommonServiceItemRoutingRequestItem struct {
	Provider Provider                                        `json:"Provider"`
	Settings PostCommonServiceItemRoutingRequestItemSettings `json:"Settings"`
}

// GetProvider returns the value of Provider.
func (s *PostCommonServiceItemRoutingRequestItem) GetProvider() Provider {
	return s.Provider
}

// GetSettings returns the value of Settings.
func (s *PostCommonServiceItemRoutingRequestItem) GetSettings() PostCommonServiceItemRoutingRequestItemSettings {
	return s.Settings
}

// SetProvider sets the value of Provider.
func (s *PostCommonServiceItemRoutingRequestItem) SetProvider(val Provider) {
	s.Provider = val
}

// SetSettings sets the value of Settings.
func (s *PostCommonServiceItemRoutingRequestItem) SetSettings(val PostCommonServiceItemRoutingRequestItemSettings) {
	s.Settings = val
}

type PostCommonServiceItemRoutingRequestItemSettings struct {
	MatchLabels   []PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem `json:"MatchLabels"`
	SourceID      string                                                           `json:"SourceID"`
	TargetGroupID string                                                           `json:"TargetGroupID"`
}

// GetMatchLabels returns the value of MatchLabels.
func (s *PostCommonServiceItemRoutingRequestItemSettings) GetMatchLabels() []PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem {
	return s.MatchLabels
}

// GetSourceID returns the value of SourceID.
func (s *PostCommonServiceItemRoutingRequestItemSettings) GetSourceID() string {
	return s.SourceID
}

// GetTargetGroupID returns the value of TargetGroupID.
func (s *PostCommonServiceItemRoutingRequestItemSettings) GetTargetGroupID() string {
	return s.TargetGroupID
}

// SetMatchLabels sets the value of MatchLabels.
func (s *PostCommonServiceItemRoutingRequestItemSettings) SetMatchLabels(val []PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) {
	s.MatchLabels = val
}

// SetSourceID sets the value of SourceID.
func (s *PostCommonServiceItemRoutingRequestItemSettings) SetSourceID(val string) {
	s.SourceID = val
}

// SetTargetGroupID sets the value of TargetGroupID.
func (s *PostCommonServiceItemRoutingRequestItemSettings) SetTargetGroupID(val string) {
	s.TargetGroupID = val
}

type PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
}

// GetName returns the value of Name.
func (s *PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) SetValue(val string) {
	s.Value = val
}

// Ref: #/components/schemas/Provider
type Provider struct {
	ID           OptInt        `json:"ID"`
	Class        ProviderClass `json:"Class"`
	Name         OptString     `json:"Name"`
	ServiceClass OptString     `json:"ServiceClass"`
}

// GetID returns the value of ID.
func (s *Provider) GetID() OptInt {
	return s.ID
}

// GetClass returns the value of Class.
func (s *Provider) GetClass() ProviderClass {
	return s.Class
}

// GetName returns the value of Name.
func (s *Provider) GetName() OptString {
	return s.Name
}

// GetServiceClass returns the value of ServiceClass.
func (s *Provider) GetServiceClass() OptString {
	return s.ServiceClass
}

// SetID sets the value of ID.
func (s *Provider) SetID(val OptInt) {
	s.ID = val
}

// SetClass sets the value of Class.
func (s *Provider) SetClass(val ProviderClass) {
	s.Class = val
}

// SetName sets the value of Name.
func (s *Provider) SetName(val OptString) {
	s.Name = val
}

// SetServiceClass sets the value of ServiceClass.
func (s *Provider) SetServiceClass(val OptString) {
	s.ServiceClass = val
}

type ProviderClass string

const (
	ProviderClassSaknoticedestination ProviderClass = "saknoticedestination"
	ProviderClassSaknoticegroup       ProviderClass = "saknoticegroup"
	ProviderClassSaknoticerouting     ProviderClass = "saknoticerouting"
)

// AllValues returns all ProviderClass values.
func (ProviderClass) AllValues() []ProviderClass {
	return []ProviderClass{
		ProviderClassSaknoticedestination,
		ProviderClassSaknoticegroup,
		ProviderClassSaknoticerouting,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProviderClass) MarshalText() ([]byte, error) {
	switch s {
	case ProviderClassSaknoticedestination:
		return []byte(s), nil
	case ProviderClassSaknoticegroup:
		return []byte(s), nil
	case ProviderClassSaknoticerouting:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProviderClass) UnmarshalText(data []byte) error {
	switch ProviderClass(data) {
	case ProviderClassSaknoticedestination:
		*s = ProviderClassSaknoticedestination
		return nil
	case ProviderClassSaknoticegroup:
		*s = ProviderClassSaknoticegroup
		return nil
	case ProviderClassSaknoticerouting:
		*s = ProviderClassSaknoticerouting
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/PutCommonServiceItemRoutingReorderRequest
type PutCommonServiceItemRoutingReorderRequest struct {
	Orders []PutCommonServiceItemRoutingReorderRequestOrdersItem `json:"Orders"`
}

// GetOrders returns the value of Orders.
func (s *PutCommonServiceItemRoutingReorderRequest) GetOrders() []PutCommonServiceItemRoutingReorderRequestOrdersItem {
	return s.Orders
}

// SetOrders sets the value of Orders.
func (s *PutCommonServiceItemRoutingReorderRequest) SetOrders(val []PutCommonServiceItemRoutingReorderRequestOrdersItem) {
	s.Orders = val
}

type PutCommonServiceItemRoutingReorderRequestOrdersItem struct {
	PriorityRank int    `json:"PriorityRank"`
	RoutingID    string `json:"RoutingID"`
}

// GetPriorityRank returns the value of PriorityRank.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) GetPriorityRank() int {
	return s.PriorityRank
}

// GetRoutingID returns the value of RoutingID.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) GetRoutingID() string {
	return s.RoutingID
}

// SetPriorityRank sets the value of PriorityRank.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) SetPriorityRank(val int) {
	s.PriorityRank = val
}

// SetRoutingID sets the value of RoutingID.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) SetRoutingID(val string) {
	s.RoutingID = val
}

// Ref: #/components/schemas/PutCommonServiceItemRoutingRequest
type PutCommonServiceItemRoutingRequest struct {
	CommonServiceItem PutCommonServiceItemRoutingRequestItem `json:"CommonServiceItem"`
}

// GetCommonServiceItem returns the value of CommonServiceItem.
func (s *PutCommonServiceItemRoutingRequest) GetCommonServiceItem() PutCommonServiceItemRoutingRequestItem {
	return s.CommonServiceItem
}

// SetCommonServiceItem sets the value of CommonServiceItem.
func (s *PutCommonServiceItemRoutingRequest) SetCommonServiceItem(val PutCommonServiceItemRoutingRequestItem) {
	s.CommonServiceItem = val
}

// Ref: #/components/schemas/PutCommonServiceItemRoutingRequestItem
type PutCommonServiceItemRoutingRequestItem struct {
	Settings PutCommonServiceItemRoutingRequestItemSettings `json:"Settings"`
}

// GetSettings returns the value of Settings.
func (s *PutCommonServiceItemRoutingRequestItem) GetSettings() PutCommonServiceItemRoutingRequestItemSettings {
	return s.Settings
}

// SetSettings sets the value of Settings.
func (s *PutCommonServiceItemRoutingRequestItem) SetSettings(val PutCommonServiceItemRoutingRequestItemSettings) {
	s.Settings = val
}

type PutCommonServiceItemRoutingRequestItemSettings struct {
	MatchLabels   []PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem `json:"MatchLabels"`
	SourceID      string                                                          `json:"SourceID"`
	TargetGroupID string                                                          `json:"TargetGroupID"`
}

// GetMatchLabels returns the value of MatchLabels.
func (s *PutCommonServiceItemRoutingRequestItemSettings) GetMatchLabels() []PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem {
	return s.MatchLabels
}

// GetSourceID returns the value of SourceID.
func (s *PutCommonServiceItemRoutingRequestItemSettings) GetSourceID() string {
	return s.SourceID
}

// GetTargetGroupID returns the value of TargetGroupID.
func (s *PutCommonServiceItemRoutingRequestItemSettings) GetTargetGroupID() string {
	return s.TargetGroupID
}

// SetMatchLabels sets the value of MatchLabels.
func (s *PutCommonServiceItemRoutingRequestItemSettings) SetMatchLabels(val []PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) {
	s.MatchLabels = val
}

// SetSourceID sets the value of SourceID.
func (s *PutCommonServiceItemRoutingRequestItemSettings) SetSourceID(val string) {
	s.SourceID = val
}

// SetTargetGroupID sets the value of TargetGroupID.
func (s *PutCommonServiceItemRoutingRequestItemSettings) SetTargetGroupID(val string) {
	s.TargetGroupID = val
}

type PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
}

// GetName returns the value of Name.
func (s *PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) GetValue() string {
	return s.Value
}

// SetName sets the value of Name.
func (s *PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) SetValue(val string) {
	s.Value = val
}

type ReorderRoutingAccepted struct {
	IsOk OptBool `json:"is_ok"`
}

// GetIsOk returns the value of IsOk.
func (s *ReorderRoutingAccepted) GetIsOk() OptBool {
	return s.IsOk
}

// SetIsOk sets the value of IsOk.
func (s *ReorderRoutingAccepted) SetIsOk(val OptBool) {
	s.IsOk = val
}
