// Copyright 2022-2025 The sacloud/simple-notification-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

// SetFake set fake values.
func (s *CommonServiceItemRouting) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemRoutingCommonServiceItem) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
	{
		{
			s.Provider.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemRoutingSettings) SetFake() {
	{
		{
			s.SourceID = "string"
		}
	}
	{
		{
			s.MatchLabels = nil
			for i := 0; i < 0; i++ {
				var elem CommonServiceItemRoutingSettingsMatchLabelsItem
				{
					elem.SetFake()
				}
				s.MatchLabels = append(s.MatchLabels, elem)
			}
		}
	}
	{
		{
			s.TargetGroupID = "string"
		}
	}
	{
		{
			s.PriorityRank = int(0)
		}
	}
}

// SetFake set fake values.
func (s *CommonServiceItemRoutingSettingsMatchLabelsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *Error) SetFake() {
	{
		{
			s.IsFatal.SetFake()
		}
	}
	{
		{
			s.Serial.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.ErrorCode.SetFake()
		}
	}
	{
		{
			s.ErrorMsg.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *NilString) SetFake() {
	s.Null = true
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilString) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptPostCommonServiceItemRoutingRequest) SetFake() {
	var elem PostCommonServiceItemRoutingRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPutCommonServiceItemRoutingReorderRequest) SetFake() {
	var elem PutCommonServiceItemRoutingReorderRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPutCommonServiceItemRoutingRequest) SetFake() {
	var elem PutCommonServiceItemRoutingRequest
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *PostCommonServiceItemRoutingRequest) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PostCommonServiceItemRoutingRequestItem) SetFake() {
	{
		{
			s.Provider.SetFake()
		}
	}
	{
		{
			s.Settings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PostCommonServiceItemRoutingRequestItemSettings) SetFake() {
	{
		{
			s.MatchLabels = nil
			for i := 0; i < 0; i++ {
				var elem PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem
				{
					elem.SetFake()
				}
				s.MatchLabels = append(s.MatchLabels, elem)
			}
		}
	}
	{
		{
			s.SourceID = "string"
		}
	}
	{
		{
			s.TargetGroupID = "string"
		}
	}
}

// SetFake set fake values.
func (s *PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *Provider) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Class.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.ServiceClass.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ProviderClass) SetFake() {
	*s = ProviderClassSaknoticedestination
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingReorderRequest) SetFake() {
	{
		{
			s.Orders = nil
			for i := 0; i < 0; i++ {
				var elem PutCommonServiceItemRoutingReorderRequestOrdersItem
				{
					elem.SetFake()
				}
				s.Orders = append(s.Orders, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingReorderRequestOrdersItem) SetFake() {
	{
		{
			s.PriorityRank = int(0)
		}
	}
	{
		{
			s.RoutingID = "string"
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingRequest) SetFake() {
	{
		{
			s.CommonServiceItem.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingRequestItem) SetFake() {
	{
		{
			s.Settings.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingRequestItemSettings) SetFake() {
	{
		{
			s.MatchLabels = nil
			for i := 0; i < 0; i++ {
				var elem PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem
				{
					elem.SetFake()
				}
				s.MatchLabels = append(s.MatchLabels, elem)
			}
		}
	}
	{
		{
			s.SourceID = "string"
		}
	}
	{
		{
			s.TargetGroupID = "string"
		}
	}
}

// SetFake set fake values.
func (s *PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Value = "string"
		}
	}
}

// SetFake set fake values.
func (s *ReorderRoutingAccepted) SetFake() {
	{
		{
			s.IsOk.SetFake()
		}
	}
}
