// Copyright 2022-2025 The sacloud/simple-notification-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	std "encoding/json"
	"testing"

	"github.com/go-faster/jx"
	"github.com/stretchr/testify/require"
)

func TestCommonServiceItemRouting_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemRouting
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemRouting
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemRoutingCommonServiceItem_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemRoutingCommonServiceItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemRoutingCommonServiceItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemRoutingSettings_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemRoutingSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemRoutingSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemRoutingSettingsMatchLabelsItem_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemRoutingSettingsMatchLabelsItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemRoutingSettingsMatchLabelsItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestError_EncodeDecode(t *testing.T) {
	var typ Error
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 Error
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRoutingRequest_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRoutingRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRoutingRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRoutingRequestItem_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRoutingRequestItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRoutingRequestItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRoutingRequestItemSettings_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRoutingRequestItemSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRoutingRequestItemSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestProvider_EncodeDecode(t *testing.T) {
	var typ Provider
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 Provider
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestProviderClass_EncodeDecode(t *testing.T) {
	var typ ProviderClass
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ProviderClass
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingReorderRequest_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingReorderRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingReorderRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingReorderRequestOrdersItem_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingReorderRequestOrdersItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingReorderRequestOrdersItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingRequest_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingRequestItem_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingRequestItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingRequestItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingRequestItemSettings_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingRequestItemSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingRequestItemSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingRequestItemSettingsMatchLabelsItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReorderRoutingAccepted_EncodeDecode(t *testing.T) {
	var typ ReorderRoutingAccepted
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReorderRoutingAccepted
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
