// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCommonServiceItemOperation    OperationName = "CreateCommonServiceItem"
	DeleteCommonServiceItemOperation    OperationName = "DeleteCommonServiceItem"
	GetCommonServiceItemOperation       OperationName = "GetCommonServiceItem"
	GetCommonServiceItemStatusOperation OperationName = "GetCommonServiceItemStatus"
	GetNotificationHistoryOperation     OperationName = "GetNotificationHistory"
	ListCommonServiceItemsOperation     OperationName = "ListCommonServiceItems"
	ListNotificationHistoriesOperation  OperationName = "ListNotificationHistories"
	ReorderRoutingOperation             OperationName = "ReorderRouting"
	SendNotificationMessageOperation    OperationName = "SendNotificationMessage"
	UpdateCommonServiceItemOperation    OperationName = "UpdateCommonServiceItem"
)
