// Copyright 2022-2025 The sacloud/simple-notification-api-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateRouting invokes createRouting operation.
	//
	// Create CommonServiceItem for Simple Notification Routing.
	//
	// POST /commonserviceitem
	CreateRouting(ctx context.Context, request OptPostCommonServiceItemRoutingRequest) (*CommonServiceItemRouting, error)
	// DeleteRouting invokes deleteRouting operation.
	//
	// Delete CommonServiceItem for Simple Notification Routing.
	//
	// DELETE /commonserviceitem/{id}
	DeleteRouting(ctx context.Context, params DeleteRoutingParams) (*CommonServiceItemRouting, error)
	// GetRouting invokes getRouting operation.
	//
	// Get CommonServiceItem for Simple Notification Routing.
	//
	// GET /commonserviceitem/{id}
	GetRouting(ctx context.Context, params GetRoutingParams) (*CommonServiceItemRouting, error)
	// ReorderRouting invokes reorderRouting operation.
	//
	// Reorder Routing priorities for Simple Notification Routing.
	//
	// PUT /commonserviceitem/simplenotification/routing/reorder
	ReorderRouting(ctx context.Context, request OptPutCommonServiceItemRoutingReorderRequest) (*ReorderRoutingAccepted, error)
	// UpdateRouting invokes updateRouting operation.
	//
	// Update CommonServiceItem for Simple Notification Routing.
	//
	// PUT /commonserviceitem/{id}
	UpdateRouting(ctx context.Context, request OptPutCommonServiceItemRoutingRequest, params UpdateRoutingParams) (*CommonServiceItemRouting, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CreateRouting invokes createRouting operation.
//
// Create CommonServiceItem for Simple Notification Routing.
//
// POST /commonserviceitem
func (c *Client) CreateRouting(ctx context.Context, request OptPostCommonServiceItemRoutingRequest) (*CommonServiceItemRouting, error) {
	res, err := c.sendCreateRouting(ctx, request)
	return res, err
}

func (c *Client) sendCreateRouting(ctx context.Context, request OptPostCommonServiceItemRoutingRequest) (res *CommonServiceItemRouting, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/commonserviceitem"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateRoutingRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCreateRoutingResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteRouting invokes deleteRouting operation.
//
// Delete CommonServiceItem for Simple Notification Routing.
//
// DELETE /commonserviceitem/{id}
func (c *Client) DeleteRouting(ctx context.Context, params DeleteRoutingParams) (*CommonServiceItemRouting, error) {
	res, err := c.sendDeleteRouting(ctx, params)
	return res, err
}

func (c *Client) sendDeleteRouting(ctx context.Context, params DeleteRoutingParams) (res *CommonServiceItemRouting, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDeleteRoutingResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetRouting invokes getRouting operation.
//
// Get CommonServiceItem for Simple Notification Routing.
//
// GET /commonserviceitem/{id}
func (c *Client) GetRouting(ctx context.Context, params GetRoutingParams) (*CommonServiceItemRouting, error) {
	res, err := c.sendGetRouting(ctx, params)
	return res, err
}

func (c *Client) sendGetRouting(ctx context.Context, params GetRoutingParams) (res *CommonServiceItemRouting, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetRoutingResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReorderRouting invokes reorderRouting operation.
//
// Reorder Routing priorities for Simple Notification Routing.
//
// PUT /commonserviceitem/simplenotification/routing/reorder
func (c *Client) ReorderRouting(ctx context.Context, request OptPutCommonServiceItemRoutingReorderRequest) (*ReorderRoutingAccepted, error) {
	res, err := c.sendReorderRouting(ctx, request)
	return res, err
}

func (c *Client) sendReorderRouting(ctx context.Context, request OptPutCommonServiceItemRoutingReorderRequest) (res *ReorderRoutingAccepted, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/commonserviceitem/simplenotification/routing/reorder"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeReorderRoutingRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeReorderRoutingResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpdateRouting invokes updateRouting operation.
//
// Update CommonServiceItem for Simple Notification Routing.
//
// PUT /commonserviceitem/{id}
func (c *Client) UpdateRouting(ctx context.Context, request OptPutCommonServiceItemRoutingRequest, params UpdateRoutingParams) (*CommonServiceItemRouting, error) {
	res, err := c.sendUpdateRouting(ctx, request, params)
	return res, err
}

func (c *Client) sendUpdateRouting(ctx context.Context, request OptPutCommonServiceItemRoutingRequest, params UpdateRoutingParams) (res *CommonServiceItemRouting, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpdateRoutingRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeUpdateRoutingResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
