// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateCommonServiceItem invokes createCommonServiceItem operation.
	//
	// リソースの作成。`Provider.
	// Class`の値に応じて必要な`Settings`の内容が異なります。.
	//
	// POST /commonserviceitem
	CreateCommonServiceItem(ctx context.Context, request OptPostCommonServiceItemRequest) (*CreateCommonServiceItemOK, error)
	// DeleteCommonServiceItem invokes deleteCommonServiceItem operation.
	//
	// リソースの削除。.
	//
	// DELETE /commonserviceitem/{id}
	DeleteCommonServiceItem(ctx context.Context, params DeleteCommonServiceItemParams) (*DeleteCommonServiceItemOK, error)
	// GetCommonServiceItem invokes getCommonServiceItem operation.
	//
	// リソースの取得。取得された`CommonServiceItem`の`Provider.
	// Class`の値に応じて`Settings`の内容は異なります。.
	//
	// GET /commonserviceitem/{id}
	GetCommonServiceItem(ctx context.Context, params GetCommonServiceItemParams) (*GetCommonServiceItemOK, error)
	// GetCommonServiceItemStatus invokes getCommonServiceItemStatus operation.
	//
	// 通知先が通知送信可能かどうかのステータス情報を取得します。.
	//
	// GET /commonserviceitem/{id}/simplenotification/status
	GetCommonServiceItemStatus(ctx context.Context, params GetCommonServiceItemStatusParams) (*GetCommonServiceItemStatusResponse, error)
	// GetNotificationHistory invokes getNotificationHistory operation.
	//
	// 指定した`request_id`に対応する通知履歴の取得。.
	//
	// GET /commonserviceitem/simplenotification/history/{request_id}
	GetNotificationHistory(ctx context.Context, params GetNotificationHistoryParams) (*GetSimpleNotificationHistoryResponse, error)
	// ListCommonServiceItems invokes listCommonServiceItems operation.
	//
	// リソースの一覧取得。クエリパラメータにて下記のように`Provider.
	// Class`を指定してフィルタを設定することで通知先、通知先グループまたは通知ルーティングのリソースのみを取得できます。
	// - 通知先: `/commonserviceitem?{"Filter":{"Provider.Class":"saknoticedestination"}}`<br>
	// - 通知先グループ: `/commonserviceitem?{"Filter":{"Provider.Class":"saknoticegroup"}}`<br>
	// - 通知ルーティング: `/commonserviceitem?{"Filter":{"Provider.Class":"saknoticerouting"}}`.
	//
	// GET /commonserviceitem
	ListCommonServiceItems(ctx context.Context) (*ListCommonServiceItemsResponse, error)
	// ListNotificationHistories invokes listNotificationHistories operation.
	//
	// 通知履歴の一覧取得。
	// 直近30日間以内の通知送信履歴が最大100件まで取得可能です。.
	//
	// GET /commonserviceitem/simplenotification/history
	ListNotificationHistories(ctx context.Context) (*ListSimpleNotificationHistoriesResponse, error)
	// ReorderRouting invokes reorderRouting operation.
	//
	// 通知ルーティングの優先順位を並び替えます。
	// `PriorityRank`の値は他の通知ルーティングと重複しないように指定する必要があります。.
	//
	// PUT /commonserviceitem/simplenotification/routing/reorder
	ReorderRouting(ctx context.Context, request OptPutCommonServiceItemRoutingReorderRequest) (*ReorderRoutingAccepted, error)
	// SendNotificationMessage invokes sendNotificationMessage operation.
	//
	// 指定した通知先グループに対してメッセージを送信します。.
	//
	// POST /commonserviceitem/{id}/simplenotification/message
	SendNotificationMessage(ctx context.Context, request OptSendNotificationMessageRequest, params SendNotificationMessageParams) (*SendNotificationMessageResponse, error)
	// UpdateCommonServiceItem invokes updateCommonServiceItem operation.
	//
	// リソースの更新。更新される`CommonServiceItem`の`Provider.
	// Class`の値に応じて`Settings`の内容は異なります。.
	//
	// PUT /commonserviceitem/{id}
	UpdateCommonServiceItem(ctx context.Context, request OptPutCommonServiceItemRequest, params UpdateCommonServiceItemParams) (*UpdateCommonServiceItemOK, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CreateCommonServiceItem invokes createCommonServiceItem operation.
//
// リソースの作成。`Provider.
// Class`の値に応じて必要な`Settings`の内容が異なります。.
//
// POST /commonserviceitem
func (c *Client) CreateCommonServiceItem(ctx context.Context, request OptPostCommonServiceItemRequest) (*CreateCommonServiceItemOK, error) {
	res, err := c.sendCreateCommonServiceItem(ctx, request)
	return res, err
}

func (c *Client) sendCreateCommonServiceItem(ctx context.Context, request OptPostCommonServiceItemRequest) (res *CreateCommonServiceItemOK, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/commonserviceitem"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateCommonServiceItemRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCreateCommonServiceItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteCommonServiceItem invokes deleteCommonServiceItem operation.
//
// リソースの削除。.
//
// DELETE /commonserviceitem/{id}
func (c *Client) DeleteCommonServiceItem(ctx context.Context, params DeleteCommonServiceItemParams) (*DeleteCommonServiceItemOK, error) {
	res, err := c.sendDeleteCommonServiceItem(ctx, params)
	return res, err
}

func (c *Client) sendDeleteCommonServiceItem(ctx context.Context, params DeleteCommonServiceItemParams) (res *DeleteCommonServiceItemOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDeleteCommonServiceItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetCommonServiceItem invokes getCommonServiceItem operation.
//
// リソースの取得。取得された`CommonServiceItem`の`Provider.
// Class`の値に応じて`Settings`の内容は異なります。.
//
// GET /commonserviceitem/{id}
func (c *Client) GetCommonServiceItem(ctx context.Context, params GetCommonServiceItemParams) (*GetCommonServiceItemOK, error) {
	res, err := c.sendGetCommonServiceItem(ctx, params)
	return res, err
}

func (c *Client) sendGetCommonServiceItem(ctx context.Context, params GetCommonServiceItemParams) (res *GetCommonServiceItemOK, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetCommonServiceItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetCommonServiceItemStatus invokes getCommonServiceItemStatus operation.
//
// 通知先が通知送信可能かどうかのステータス情報を取得します。.
//
// GET /commonserviceitem/{id}/simplenotification/status
func (c *Client) GetCommonServiceItemStatus(ctx context.Context, params GetCommonServiceItemStatusParams) (*GetCommonServiceItemStatusResponse, error) {
	res, err := c.sendGetCommonServiceItemStatus(ctx, params)
	return res, err
}

func (c *Client) sendGetCommonServiceItemStatus(ctx context.Context, params GetCommonServiceItemStatusParams) (res *GetCommonServiceItemStatusResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/simplenotification/status"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetCommonServiceItemStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetNotificationHistory invokes getNotificationHistory operation.
//
// 指定した`request_id`に対応する通知履歴の取得。.
//
// GET /commonserviceitem/simplenotification/history/{request_id}
func (c *Client) GetNotificationHistory(ctx context.Context, params GetNotificationHistoryParams) (*GetSimpleNotificationHistoryResponse, error) {
	res, err := c.sendGetNotificationHistory(ctx, params)
	return res, err
}

func (c *Client) sendGetNotificationHistory(ctx context.Context, params GetNotificationHistoryParams) (res *GetSimpleNotificationHistoryResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/commonserviceitem/simplenotification/history/"
	{
		// Encode "request_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "request_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.RequestID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetNotificationHistoryResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListCommonServiceItems invokes listCommonServiceItems operation.
//
// リソースの一覧取得。クエリパラメータにて下記のように`Provider.
// Class`を指定してフィルタを設定することで通知先、通知先グループまたは通知ルーティングのリソースのみを取得できます。
// - 通知先: `/commonserviceitem?{"Filter":{"Provider.Class":"saknoticedestination"}}`<br>
// - 通知先グループ: `/commonserviceitem?{"Filter":{"Provider.Class":"saknoticegroup"}}`<br>
// - 通知ルーティング: `/commonserviceitem?{"Filter":{"Provider.Class":"saknoticerouting"}}`.
//
// GET /commonserviceitem
func (c *Client) ListCommonServiceItems(ctx context.Context) (*ListCommonServiceItemsResponse, error) {
	res, err := c.sendListCommonServiceItems(ctx)
	return res, err
}

func (c *Client) sendListCommonServiceItems(ctx context.Context) (res *ListCommonServiceItemsResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/commonserviceitem"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeListCommonServiceItemsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListNotificationHistories invokes listNotificationHistories operation.
//
// 通知履歴の一覧取得。
// 直近30日間以内の通知送信履歴が最大100件まで取得可能です。.
//
// GET /commonserviceitem/simplenotification/history
func (c *Client) ListNotificationHistories(ctx context.Context) (*ListSimpleNotificationHistoriesResponse, error) {
	res, err := c.sendListNotificationHistories(ctx)
	return res, err
}

func (c *Client) sendListNotificationHistories(ctx context.Context) (res *ListSimpleNotificationHistoriesResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/commonserviceitem/simplenotification/history"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeListNotificationHistoriesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReorderRouting invokes reorderRouting operation.
//
// 通知ルーティングの優先順位を並び替えます。
// `PriorityRank`の値は他の通知ルーティングと重複しないように指定する必要があります。.
//
// PUT /commonserviceitem/simplenotification/routing/reorder
func (c *Client) ReorderRouting(ctx context.Context, request OptPutCommonServiceItemRoutingReorderRequest) (*ReorderRoutingAccepted, error) {
	res, err := c.sendReorderRouting(ctx, request)
	return res, err
}

func (c *Client) sendReorderRouting(ctx context.Context, request OptPutCommonServiceItemRoutingReorderRequest) (res *ReorderRoutingAccepted, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/commonserviceitem/simplenotification/routing/reorder"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeReorderRoutingRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeReorderRoutingResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SendNotificationMessage invokes sendNotificationMessage operation.
//
// 指定した通知先グループに対してメッセージを送信します。.
//
// POST /commonserviceitem/{id}/simplenotification/message
func (c *Client) SendNotificationMessage(ctx context.Context, request OptSendNotificationMessageRequest, params SendNotificationMessageParams) (*SendNotificationMessageResponse, error) {
	res, err := c.sendSendNotificationMessage(ctx, request, params)
	return res, err
}

func (c *Client) sendSendNotificationMessage(ctx context.Context, request OptSendNotificationMessageRequest, params SendNotificationMessageParams) (res *SendNotificationMessageResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/simplenotification/message"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSendNotificationMessageRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeSendNotificationMessageResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpdateCommonServiceItem invokes updateCommonServiceItem operation.
//
// リソースの更新。更新される`CommonServiceItem`の`Provider.
// Class`の値に応じて`Settings`の内容は異なります。.
//
// PUT /commonserviceitem/{id}
func (c *Client) UpdateCommonServiceItem(ctx context.Context, request OptPutCommonServiceItemRequest, params UpdateCommonServiceItemParams) (*UpdateCommonServiceItemOK, error) {
	res, err := c.sendUpdateCommonServiceItem(ctx, request, params)
	return res, err
}

func (c *Client) sendUpdateCommonServiceItem(ctx context.Context, request OptPutCommonServiceItemRequest, params UpdateCommonServiceItemParams) (res *UpdateCommonServiceItemOK, err error) {
	// Validate request before sending.
	if err := func() error {
		if value, ok := request.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/commonserviceitem/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpdateCommonServiceItemRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeUpdateCommonServiceItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
