// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/validate"

	std "encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestCommonServiceItem_EncodeDecode(t *testing.T) {
	var typ CommonServiceItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemDestinationSettings_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemDestinationSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemDestinationSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemDestinationSettingsType_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemDestinationSettingsType
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemDestinationSettingsType
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemGroupSettings_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemGroupSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemGroupSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemProvider_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemProvider
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemProvider
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemProviderClass_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemProviderClass
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemProviderClass
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemRoutingSettings_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemRoutingSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemRoutingSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemRoutingSettingsMatchLabelsItem_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemRoutingSettingsMatchLabelsItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemRoutingSettingsMatchLabelsItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCommonServiceItemSettings_EncodeDecode(t *testing.T) {
	var typ CommonServiceItemSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CommonServiceItemSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCreateCommonServiceItemCreated_EncodeDecode(t *testing.T) {
	var typ CreateCommonServiceItemCreated
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CreateCommonServiceItemCreated
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestDeleteCommonServiceItemOK_EncodeDecode(t *testing.T) {
	var typ DeleteCommonServiceItemOK
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 DeleteCommonServiceItemOK
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestError_EncodeDecode(t *testing.T) {
	var typ Error
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 Error
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGetCommonServiceItemOK_EncodeDecode(t *testing.T) {
	var typ GetCommonServiceItemOK
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetCommonServiceItemOK
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestGetCommonServiceItemOK_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "{\"CommonServiceItem\":{\"CreatedAt\":\"2026-12-18T12:00:00+09:00\",\"Description\":\"メール通知先の説明\",\"ID\":\"123700010001\",\"Icon\":{},\"ModifiedAt\":\"2026-12-18T12:00:00+09:00\",\"Name\":\"mail destination\",\"Provider\":{\"Class\":\"saknoticedestination\"},\"Settings\":{\"Type\":\"email\",\"Value\":\"user@example.com\"},\"Tags\":[]}}"},
		{Input: "{\"CommonServiceItem\":{\"CreatedAt\":\"2026-12-18T12:00:00+09:00\",\"Description\":\"通知ルーティングの説明\",\"ID\":\"123700030001\",\"Icon\":{},\"ModifiedAt\":\"2026-12-18T12:00:00+09:00\",\"Name\":\"test routing\",\"Provider\":{\"Class\":\"saknoticerouting\"},\"Settings\":{\"MatchLabels\":[{\"Name\":\"environment\",\"Value\":\"development\"}],\"PriorityRank\":1,\"SourceID\":\"1\",\"TargetGroupID\":\"123700020001\"},\"Tags\":[]}}"},
		{Input: "{\"CommonServiceItem\":{\"CreatedAt\":\"2026-12-18T12:00:00+09:00\",\"Description\":\"通知先グループの説明\",\"ID\":\"123700020001\",\"Icon\":{},\"ModifiedAt\":\"2026-12-18T12:00:00+09:00\",\"Name\":\"test group\",\"Provider\":{\"Class\":\"saknoticegroup\"},\"Settings\":{\"Destinations\":[\"123700010001\",\"123700010002\"]},\"Tags\":[]}}"},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ GetCommonServiceItemOK

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 GetCommonServiceItemOK
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
func TestGetCommonServiceItemStatusResponse_EncodeDecode(t *testing.T) {
	var typ GetCommonServiceItemStatusResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetCommonServiceItemStatusResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGetCommonServiceItemStatusResponseNotificationStatus_EncodeDecode(t *testing.T) {
	var typ GetCommonServiceItemStatusResponseNotificationStatus
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetCommonServiceItemStatusResponseNotificationStatus
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGetSimpleNotificationHistoryResponse_EncodeDecode(t *testing.T) {
	var typ GetSimpleNotificationHistoryResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetSimpleNotificationHistoryResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestGetSimpleNotificationHistoryResponse_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "{\"NotificationHistory\":{\"message\":{\"body\":\"This is a test notification message.\",\"color\":\"default\",\"color_code\":\"#7d7d7d\",\"icon_url\":\"https://example.com/icon.png\",\"image_url\":\"https://example.com/image.png\",\"title\":\"Test Notification\"},\"received_at\":\"2026-12-18T12:00:00+09:00\",\"request_id\":\"12345\",\"source_id\":\"\",\"statuses\":[{\"created_at\":\"2026-12-18T12:00:00+09:00\",\"destination_id\":\"123700010001\",\"error_info\":\"\",\"group_id\":\"123700020001\",\"id\":\"67890\",\"notification_request_id\":\"12345\",\"status\":2,\"updated_at\":\"2026-12-18T12:05:00+09:00\"}]}}"},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ GetSimpleNotificationHistoryResponse

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 GetSimpleNotificationHistoryResponse
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
func TestIcon_EncodeDecode(t *testing.T) {
	var typ Icon
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 Icon
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestListCommonServiceItemsResponse_EncodeDecode(t *testing.T) {
	var typ ListCommonServiceItemsResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ListCommonServiceItemsResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestListCommonServiceItemsResponse_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "{\"CommonServiceItems\":[{\"CreatedAt\":\"2026-12-18T12:00:00+09:00\",\"Description\":\"メール通知先の説明\",\"ID\":\"123700010001\",\"Icon\":{},\"Index\":0,\"ModifiedAt\":\"2026-12-18T12:00:00+09:00\",\"Name\":\"mail destination\",\"Provider\":{\"Class\":\"saknoticedestination\"},\"Settings\":{\"Type\":\"email\",\"Value\":\"user@example.com\"},\"Tags\":[]},{\"CreatedAt\":\"2026-12-18T12:00:00+09:00\",\"Description\":\"Webhook通知先の説明\",\"ID\":\"123700010002\",\"Icon\":{},\"Index\":1,\"ModifiedAt\":\"2026-12-18T12:00:00+09:00\",\"Name\":\"webhook destination\",\"Provider\":{\"Class\":\"saknoticedestination\"},\"Settings\":{\"Type\":\"webhook\",\"Value\":\"https://example.com/notify\"},\"Tags\":[]}],\"Count\":2,\"From\":0,\"Total\":2}"},
		{Input: "{\"CommonServiceItems\":[{\"CreatedAt\":\"2026-12-18T12:00:00+09:00\",\"Description\":\"通知ルーティングの説明\",\"ID\":\"123700030001\",\"Icon\":{},\"Index\":0,\"ModifiedAt\":\"2026-12-18T12:00:00+09:00\",\"Name\":\"test routing\",\"Provider\":{\"Class\":\"saknoticerouting\"},\"Settings\":{\"MatchLabels\":[{\"Name\":\"environment\",\"Value\":\"development\"}],\"PriorityRank\":1,\"SourceID\":\"1\",\"TargetGroupID\":\"123700020001\"},\"Tags\":[]}],\"Count\":1,\"From\":0,\"Total\":1}"},
		{Input: "{\"CommonServiceItems\":[{\"CreatedAt\":\"2026-12-18T12:00:00+09:00\",\"Description\":\"通知先グループの説明\",\"ID\":\"123700020001\",\"Icon\":{},\"Index\":0,\"ModifiedAt\":\"2026-12-18T12:00:00+09:00\",\"Name\":\"test group\",\"Provider\":{\"Class\":\"saknoticegroup\"},\"Settings\":{\"Destinations\":[\"123700010001\",\"123700010002\"]},\"Tags\":[]}],\"Count\":1,\"From\":0,\"Total\":1}"},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ ListCommonServiceItemsResponse

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 ListCommonServiceItemsResponse
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
func TestListSimpleNotificationHistoriesResponse_EncodeDecode(t *testing.T) {
	var typ ListSimpleNotificationHistoriesResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ListSimpleNotificationHistoriesResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestListSimpleNotificationHistoriesResponse_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "{\"NotificationHistories\":[{\"message\":{\"body\":\"This is a test notification message.\",\"color\":\"default\",\"color_code\":\"#7d7d7d\",\"icon_url\":\"https://example.com/icon.png\",\"image_url\":\"https://example.com/image.png\",\"title\":\"Test Notification\"},\"received_at\":\"2026-12-18T12:00:00+09:00\",\"request_id\":\"12345\",\"source_id\":\"\",\"statuses\":[{\"created_at\":\"2026-12-18T12:00:00+09:00\",\"destination_id\":\"123700010001\",\"error_info\":\"\",\"group_id\":\"123700020001\",\"id\":\"67890\",\"notification_request_id\":\"12345\",\"status\":2,\"updated_at\":\"2026-12-18T12:05:00+09:00\"}]}]}"},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ ListSimpleNotificationHistoriesResponse

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 ListSimpleNotificationHistoriesResponse
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
func TestListSourcesResponse_EncodeDecode(t *testing.T) {
	var typ ListSourcesResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ListSourcesResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestListSourcesResponseSourcesItem_EncodeDecode(t *testing.T) {
	var typ ListSourcesResponseSourcesItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ListSourcesResponseSourcesItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestNotificationHistory_EncodeDecode(t *testing.T) {
	var typ NotificationHistory
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 NotificationHistory
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestNotificationMessage_EncodeDecode(t *testing.T) {
	var typ NotificationMessage
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 NotificationMessage
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestNotificationStatus_EncodeDecode(t *testing.T) {
	var typ NotificationStatus
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 NotificationStatus
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestNotificationStatusStatus_EncodeDecode(t *testing.T) {
	var typ NotificationStatusStatus
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 NotificationStatusStatus
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRequest_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestPostCommonServiceItemRequest_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "{\"CommonServiceItem\":{\"Description\":\"メール通知先の説明\",\"Icon\":{},\"Name\":\"mail destination\",\"Provider\":{\"Class\":\"saknoticedestination\"},\"Settings\":{\"Type\":\"email\",\"Value\":\"user@example.com\"},\"Tags\":[]}}"},
		{Input: "{\"CommonServiceItem\":{\"Description\":\"通知ルーティングの説明\",\"Icon\":{},\"Name\":\"test routing\",\"Provider\":{\"Class\":\"saknoticerouting\"},\"Settings\":{\"MatchLabels\":[{\"Name\":\"environment\",\"Value\":\"development\"}],\"SourceID\":\"1\",\"TargetGroupID\":\"123700020001\"},\"Tags\":[]}}"},
		{Input: "{\"CommonServiceItem\":{\"Description\":\"通知先グループの説明\",\"Icon\":{},\"Name\":\"test group\",\"Provider\":{\"Class\":\"saknoticegroup\"},\"Settings\":{\"Destinations\":[\"123700010001\"]},\"Tags\":[]}}"},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ PostCommonServiceItemRequest

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 PostCommonServiceItemRequest
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
func TestPostCommonServiceItemRequestCommonServiceItem_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRequestCommonServiceItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRequestCommonServiceItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRequestCommonServiceItemProvider_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRequestCommonServiceItemProvider
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRequestCommonServiceItemProvider
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRequestCommonServiceItemProviderClass_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRequestCommonServiceItemProviderClass
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRequestCommonServiceItemProviderClass
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPostCommonServiceItemRequestCommonServiceItemSettings_EncodeDecode(t *testing.T) {
	var typ PostCommonServiceItemRequestCommonServiceItemSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PostCommonServiceItemRequestCommonServiceItemSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRequest_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestPutCommonServiceItemRequest_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "{\"CommonServiceItem\":{\"Description\":\"メール通知先の説明\",\"Icon\":{},\"Name\":\"mail destination\",\"Settings\":{\"Type\":\"email\",\"Value\":\"user@example.com\"},\"Tags\":[]}}"},
		{Input: "{\"CommonServiceItem\":{\"Description\":\"通知ルーティングの説明\",\"Icon\":{},\"Name\":\"test routing\",\"Settings\":{\"MatchLabels\":[{\"Name\":\"environment\",\"Value\":\"development\"}],\"SourceID\":\"1\",\"TargetGroupID\":\"123700020001\"},\"Tags\":[]}}"},
		{Input: "{\"CommonServiceItem\":{\"Description\":\"通知先グループの説明\",\"Icon\":{},\"Name\":\"test group\",\"Settings\":{\"Destinations\":[\"123700010001\"]},\"Tags\":[]}}"},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ PutCommonServiceItemRequest

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 PutCommonServiceItemRequest
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
func TestPutCommonServiceItemRequestCommonServiceItem_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRequestCommonServiceItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRequestCommonServiceItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRequestCommonServiceItemSettings_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRequestCommonServiceItemSettings
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRequestCommonServiceItemSettings
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingReorderRequest_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingReorderRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingReorderRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPutCommonServiceItemRoutingReorderRequestOrdersItem_EncodeDecode(t *testing.T) {
	var typ PutCommonServiceItemRoutingReorderRequestOrdersItem
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PutCommonServiceItemRoutingReorderRequestOrdersItem
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestReorderRoutingAccepted_EncodeDecode(t *testing.T) {
	var typ ReorderRoutingAccepted
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 ReorderRoutingAccepted
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestSendNotificationMessageRequest_EncodeDecode(t *testing.T) {
	var typ SendNotificationMessageRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 SendNotificationMessageRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestSendNotificationMessageResponse_EncodeDecode(t *testing.T) {
	var typ SendNotificationMessageResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 SendNotificationMessageResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestUpdateCommonServiceItemOK_EncodeDecode(t *testing.T) {
	var typ UpdateCommonServiceItemOK
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 UpdateCommonServiceItemOK
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
